In [57]:
import pandas as pd
import csv 
import math

In [58]:
dataset = pd.read_csv('./dataset.csv')
dataset.tail()

,index,img_url,prod_url,price,5,4,3,2,1
175,916,https://images.meesho.com/images/products/1570...,https://www.meesho.com/adrika-voguish-kurtis/p...,₹503,172,65,53,45,70
176,917,https://images.meesho.com/images/products/1400...,https://www.meesho.com/trendy-fashionable-kurt...,₹434,373,130,57,24,74
177,918,https://images.meesho.com/images/products/4901...,https://www.meesho.com/adrika-petite-kurtis/p/...,₹261,44,22,10,9,16
178,919,https://images.meesho.com/images/products/1305...,https://www.meesho.com/aagyeyi-petite-kurtis/p...,₹478,8,9,0,1,0
179,920,https://images.meesho.com/images/products/1199...,https://www.meesho.com/womens-rayon-chikankari...,₹464,296,126,58,33,59

In [59]:
max = 12744
min = 0
new_max = 500
new_min = 0

for i in range (0,180):
    dataset.loc[i,'5'] = math.ceil((dataset.loc[i,'5']/12744)*(500))

for i in range (0,180):
    dataset.loc[i,'4'] = math.ceil((dataset.loc[i,'4']/12744)*(500))
    
for i in range (0,180):
    dataset.loc[i,'3'] = math.ceil((dataset.loc[i,'3']/12744)*(500))

for i in range (0,180):
    dataset.loc[i,'2'] = math.ceil((dataset.loc[i,'2']/12744)*(500))

for i in range (0,180):
    dataset.loc[i,'1'] = math.ceil((dataset.loc[i,'1']/12744)*(500))

    
    
dataset.to_csv('dataset1.csv' , index = False)
    
dataset.head()

,index,img_url,prod_url,price,5,4,3,2,1
0,11,https://images.meesho.com/images/products/1167...,https://www.meesho.com/alisha-refined-kurtis/p...,₹293,166,64,55,40,80
1,12,https://images.meesho.com/images/products/1154...,https://www.meesho.com/chitrarekha-attractive-...,₹305,23,9,7,4,7
2,13,https://images.meesho.com/images/products/7009...,https://www.meesho.com/jivika-graceful-kurtis/...,₹429,47,22,15,11,21
3,14,https://images.meesho.com/images/products/7079...,https://www.meesho.com/abhisarika-attractive-k...,₹465,171,75,56,36,88
4,15,https://images.meesho.com/images/products/1132...,https://www.meesho.com/myra-graceful-kurtis/p/...,₹303,31,11,12,6,10