In [1]:
pip install uuid

Collecting uuid
  Downloading uuid-1.30.tar.gz (5.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: uuid
  Building wheel for uuid (setup.py): started
  Building wheel for uuid (setup.py): finished with status 'done'
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6480 sha256=7ec688c5dbc7896355a38a1ea707a612a282eac84aaa8625b7ff74104fd9d64a
  Stored in directory: c:\users\nabeel\appdata\local\pip\cache\wheels\ed\08\9e\f0a977dfe55051a07e21af89200125d65f1efa60cbac61ed88
Successfully built uuid
Installing collected packages: uuid
Successfully installed uuid-1.30
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: C:\Users\Nabeel\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [56]:
import pandas as pd
import csv 
import math
import uuid
import random
import numpy as np

In [30]:
dataset = pd.read_csv('./dataset1.csv')
dataset.tail()

,index,img_url,prod_url,price,5,4,3,2,1,SUM
175,916,https://images.meesho.com/images/products/1570...,https://www.meesho.com/adrika-voguish-kurtis/p...,₹503,7,3,3,2,3,18
176,917,https://images.meesho.com/images/products/1400...,https://www.meesho.com/trendy-fashionable-kurt...,₹434,15,6,3,1,3,28
177,918,https://images.meesho.com/images/products/4901...,https://www.meesho.com/adrika-petite-kurtis/p/...,₹261,2,1,1,1,1,6
178,919,https://images.meesho.com/images/products/1305...,https://www.meesho.com/aagyeyi-petite-kurtis/p...,₹478,1,1,0,1,0,3
179,920,https://images.meesho.com/images/products/1199...,https://www.meesho.com/womens-rayon-chikankari...,₹464,12,5,3,2,3,25

In [59]:
# max = 12744
# min = 0
# new_max = 500
# new_min = 0

# for i in range (0,180):
#     dataset.loc[i,'5'] = math.ceil((dataset.loc[i,'5']/12744)*(500))

# for i in range (0,180):
#     dataset.loc[i,'4'] = math.ceil((dataset.loc[i,'4']/12744)*(500))
    
# for i in range (0,180):
#     dataset.loc[i,'3'] = math.ceil((dataset.loc[i,'3']/12744)*(500))

# for i in range (0,180):
#     dataset.loc[i,'2'] = math.ceil((dataset.loc[i,'2']/12744)*(500))

# for i in range (0,180):
#     dataset.loc[i,'1'] = math.ceil((dataset.loc[i,'1']/12744)*(500))

    
    
# dataset.to_csv('dataset1.csv' , index = False)
    
# dataset.head()

,index,img_url,prod_url,price,5,4,3,2,1
0,11,https://images.meesho.com/images/products/1167...,https://www.meesho.com/alisha-refined-kurtis/p...,₹293,166,64,55,40,80
1,12,https://images.meesho.com/images/products/1154...,https://www.meesho.com/chitrarekha-attractive-...,₹305,23,9,7,4,7
2,13,https://images.meesho.com/images/products/7009...,https://www.meesho.com/jivika-graceful-kurtis/...,₹429,47,22,15,11,21
3,14,https://images.meesho.com/images/products/7079...,https://www.meesho.com/abhisarika-attractive-k...,₹465,171,75,56,36,88
4,15,https://images.meesho.com/images/products/1132...,https://www.meesho.com/myra-graceful-kurtis/p/...,₹303,31,11,12,6,10

In [14]:
dataset.describe()

            index           5           4           3           2           1
count  180.000000  180.000000  180.000000  180.000000  180.000000  180.000000
mean   308.000000   35.533333   15.233333   10.244444    6.333333   12.133333
std    299.742068   68.402800   28.928751   20.356494   12.337887   24.599223
min     11.000000    1.000000    1.000000    0.000000    0.000000    0.000000
25%     60.500000    5.000000    2.000000    2.000000    1.000000    2.000000
50%    118.500000   13.500000    6.000000    3.500000    2.000000    4.000000
75%    519.250000   31.000000   13.250000   10.000000    6.000000   10.000000
max    920.000000  500.000000  181.000000  140.000000   91.000000  171.000000

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     180 non-null    int64
 1   img_url   180 non-null    object
 2   prod_url  180 non-null    object
 3   price     180 non-null    object
 4   5         180 non-null    int64
 5   4         180 non-null    int64
 6   3         180 non-null    int64
 7   2         180 non-null    int64
 8   1         180 non-null    int64
dtypes: int64(6), object(3)
memory usage: 12.8+ KB

In [27]:
id = uuid.uuid4()
id.hex

'8259ca83c8b8481aaf1a1dee90bef995'

In [28]:
id

UUID('8259ca83-c8b8-481a-af1a-1dee90bef995')

In [45]:
prod_id = []
for url in dataset['prod_url']:
    url = url[url.rfind('/')+1:]
    print(url)

1xiamj
1wq4nz
15qgsz
165dfs
1vexv5
1c1wnf
p0ntb
2w7fa4
2fb25u
1ya45i
1sbsct
u9jyk
2diuvh
2breed
2du9vd
itwca
2bt64t
xs9rd
33zjt5
2ussfg
26yjil
u6hd5
epxlp
30d6hw
37mquq
345d56
25i6iz
1i4b6q
31g8jl
105mbl
8d8ha
1j9iz8
1uu42k
11w8ry
2b01ni
170kgm
18trri
xpuga
2jqfw8
17td32
328re8
w9k45
10mrkq
2z7cze
12lux0
16og1q
17uo09
1v05vs
2m0vuc
28i2s8
y7sg9
2xs130
17neom
1bi4qc
2pzgfy
235q3c
2po9mi
13v10w
30bzdz
2tym8u
2dutfj
17n994
2cdo61
2dyrwr
14g9wh
163qdn
1nm3np
2q479d
2xf8te
1ugxn1
eax23
2dot7a
1e6c6r
38vjvb
390z7l
2c1jke
s4nz0
30o21n
30e22h
qjs2q
bn7pz
zqe9o
1uwu19
24zlub
1asz9t
c585d
2n90mv
a83w9
x5ift
13bmkm
33qbeb
qy6xx
1cyb2x
2eqcbv
32yunj
2n73er
2f4lj0
37jf6j
busa3
4l2w8
28uudd
2hpf3u
2pwht3
2bhjqz
2dufra
27omrn
1wkdem
2ec5ff
2bxbic
16xjkp
28rjwx
153oib
2ogjks
21xlz4
15tluk
t2yus
2a7z9j
120mm3
1x01jd
1qw2u9
2ej0sy
zgxlp
19esey
fj9w1
2jy533
37dank
35syqk
pp1gx
wwo5c
4mah8
loyj6
33sv6n
2j8v1c
1xdlka
16j7sk
6w8vx
2j59xw
1lo4t6
2crzm2
11dj9v
2rltnv
77fni
2l7r6r
1tdtof
25uowx
21exhl
163ui6
2mvpr1
30ly7y
2c42pu
bnnlr
2ityzt
oup6v
1o6zdy
2m0vhj
38uzpk
2xs0ae
1phlwm
2sh0ht
18h6jj
1sbme8
15uiwy
2n590v
2l94bm
13zyl1
30zubv
2duoay
32vo85
1u274v
p0mtb
1f46gi
98zjw
2akdgr
38l9n6
1dbf6l
2li7yg
2bd2k0
t6j53
25qp2y
754ly

In [46]:
for i in range(0,180):
    dataset.loc[i,'prod_url'] = dataset.loc[i,'prod_url'][dataset.loc[i,'prod_url'].rfind('/')+1:]
    prod_id += [dataset.loc[i,'prod_url']]
len(prod_id)

180

In [39]:
# l = [dataset['prod_url'] , [prod_id]]
# zip(*l)
# print(l)

[0      1xiamj
1      1wq4nz
2      15qgsz
3      165dfs
4      1vexv5
        ...
175    2li7yg
176    2bd2k0
177     t6j53
178    25qp2y
179     754ly
Name: prod_url, Length: 180, dtype: object, [[<pandas.core.indexing._LocIndexer object at 0x000001D27C613560>, <pandas.core.indexing._LocIndexer object at 0x000001D27C63C540>, '1xiamj', '1wq4nz', '15qgsz', '165dfs', '1vexv5', '1c1wnf', 'p0ntb', '2w7fa4', '2fb25u', '1ya45i', '1sbsct', 'u9jyk', '2diuvh', '2breed', '2du9vd', 'itwca', '2bt64t', 'xs9rd', '33zjt5', '2ussfg', '26yjil', 'u6hd5', 'epxlp', '30d6hw', '37mquq', '345d56', '25i6iz', '1i4b6q', '31g8jl', '105mbl', '8d8ha', '1j9iz8', '1uu42k', '11w8ry', '2b01ni', '170kgm', '18trri', 'xpuga', '2jqfw8', '17td32', '328re8', 'w9k45', '10mrkq', '2z7cze', '12lux0', '16og1q', '17uo09', '1v05vs', '2m0vuc', '28i2s8', 'y7sg9', '2xs130', '17neom', '1bi4qc', '2pzgfy', '235q3c', '2po9mi', '13v10w', '30bzdz', '2tym8u', '2dutfj', '17n994', '2cdo61', '2dyrwr', '14g9wh', '163qdn', '1nm3np', '2q479d', '2xf8te', '1ugxn1', 'eax23', '2dot7a', '1e6c6r', '38vjvb', '390z7l', '2c1jke', 's4nz0', '30o21n', '30e22h', 'qjs2q', 'bn7pz', 'zqe9o', '1uwu19', '24zlub', '1asz9t', 'c585d', '2n90mv', 'a83w9', 'x5ift', '13bmkm', '33qbeb', 'qy6xx', '1cyb2x', '2eqcbv', '32yunj', '2n73er', '2f4lj0', '37jf6j', 'busa3', '4l2w8', '28uudd', '2hpf3u', '2pwht3', '2bhjqz', '2dufra', '27omrn', '1wkdem', '2ec5ff', '2bxbic', '16xjkp', '28rjwx', '153oib', '2ogjks', '21xlz4', '15tluk', 't2yus', '2a7z9j', '120mm3', '1x01jd', '1qw2u9', '2ej0sy', 'zgxlp', '19esey', 'fj9w1', '2jy533', '37dank', '35syqk', 'pp1gx', 'wwo5c', '4mah8', 'loyj6', '33sv6n', '2j8v1c', '1xdlka', '16j7sk', '6w8vx', '2j59xw', '1lo4t6', '2crzm2', '11dj9v', '2rltnv', '77fni', '2l7r6r', '1tdtof', '25uowx', '21exhl', '163ui6', '2mvpr1', '30ly7y', '2c42pu', 'bnnlr', '2ityzt', 'oup6v', '1o6zdy', '2m0vhj', '38uzpk', '2xs0ae', '1phlwm', '2sh0ht', '18h6jj', '1sbme8', '15uiwy', '2n590v', '2l94bm', '13zyl1', '30zubv', '2duoay', '32vo85', '1u274v', 'p0mtb', '1f46gi', '98zjw', '2akdgr', '38l9n6', '1dbf6l', '2li7yg', '2bd2k0', 't6j53', '25qp2y', '754ly']]]

In [48]:
dataset['prod_id'] = prod_id
dataset.to_csv('dataset2.csv' , index = False)

In [49]:
dataset = pd.read_csv('dataset2.csv')
dataset.head()

,index,img_url,prod_url,price,5,4,3,2,1,SUM,prod_id
0,11,https://images.meesho.com/images/products/1167...,1xiamj,₹293,166,64,55,40,80,405,1xiamj
1,12,https://images.meesho.com/images/products/1154...,1wq4nz,₹305,23,9,7,4,7,50,1wq4nz
2,13,https://images.meesho.com/images/products/7009...,15qgsz,₹429,47,22,15,11,21,116,15qgsz
3,14,https://images.meesho.com/images/products/7079...,165dfs,₹465,171,75,56,36,88,426,165dfs
4,15,https://images.meesho.com/images/products/1132...,1vexv5,₹303,31,11,12,6,10,70,1vexv5

In [60]:
dataset.loc[179]

index                                                     920
img_url     https://images.meesho.com/images/products/1199...
prod_url                                                754ly
price                                                    ₹464
5                                                          12
4                                                           5
3                                                           3
2                                                           2
1                                                           3
SUM                                                        25
prod_id                                                 754ly
Name: 179, dtype: object