In [1]:
pip install uuid

Collecting uuid
  Downloading uuid-1.30.tar.gz (5.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: uuid
  Building wheel for uuid (setup.py): started
  Building wheel for uuid (setup.py): finished with status 'done'
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6480 sha256=c78d3bf3506618fdf75e66e46724988ebf163ef3616f213d53db191428dca007
  Stored in directory: c:\users\pranay mahadik\appdata\local\pip\cache\wheels\05\d7\b4\4795d29c6decfffbf64c63e58b6c8b8bbfd4751488617dcd7a
Successfully built uuid
Installing collected packages: uuid
Successfully installed uuid-1.30
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import csv 
import math
import uuid
import random
import numpy as np

In [3]:
dataset = pd.read_csv('./dataset.csv')
dataset.tail()

,index,img_url,prod_url,price,5,4,3,2,1,SUM
1135,6016,https://images.meesho.com/images/products/6454...,https://www.meesho.com/aagam-fashionable-kurti...,₹479,0,0,0,0,0,0
1136,6017,https://images.meesho.com/images/products/6231...,https://www.meesho.com/chitrarekha-ensemble-ku...,₹368,5,1,1,1,1,9
1137,6018,https://images.meesho.com/images/products/5204...,https://www.meesho.com/aagyeyi-fashionable-kur...,₹533,1,3,0,1,0,5
1138,6019,https://images.meesho.com/images/products/1210...,https://www.meesho.com/abhisarika-graceful-kur...,₹565,2,2,5,1,0,10
1139,6020,https://images.meesho.com/images/products/1496...,https://www.meesho.com/chitrarekha-pretty-kurt...,₹464,0,0,0,0,0,0

In [59]:
# max = 12744
# min = 0
# new_max = 500
# new_min = 0

# for i in range (0,180):
#     dataset.loc[i,'5'] = math.ceil((dataset.loc[i,'5']/12744)*(500))

# for i in range (0,180):
#     dataset.loc[i,'4'] = math.ceil((dataset.loc[i,'4']/12744)*(500))
    
# for i in range (0,180):
#     dataset.loc[i,'3'] = math.ceil((dataset.loc[i,'3']/12744)*(500))

# for i in range (0,180):
#     dataset.loc[i,'2'] = math.ceil((dataset.loc[i,'2']/12744)*(500))

# for i in range (0,180):
#     dataset.loc[i,'1'] = math.ceil((dataset.loc[i,'1']/12744)*(500))

    
    
# dataset.to_csv('dataset1.csv' , index = False)
    
# dataset.head()

,index,img_url,prod_url,price,5,4,3,2,1
0,11,https://images.meesho.com/images/products/1167...,https://www.meesho.com/alisha-refined-kurtis/p...,₹293,166,64,55,40,80
1,12,https://images.meesho.com/images/products/1154...,https://www.meesho.com/chitrarekha-attractive-...,₹305,23,9,7,4,7
2,13,https://images.meesho.com/images/products/7009...,https://www.meesho.com/jivika-graceful-kurtis/...,₹429,47,22,15,11,21
3,14,https://images.meesho.com/images/products/7079...,https://www.meesho.com/abhisarika-attractive-k...,₹465,171,75,56,36,88
4,15,https://images.meesho.com/images/products/1132...,https://www.meesho.com/myra-graceful-kurtis/p/...,₹303,31,11,12,6,10

In [4]:
dataset.describe()

,index,5,4,3,2,1,SUM
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000
mean,1795.500000,186.907895,78.777193,51.592105,29.899123,59.229825,406.406140
std,1851.735845,673.283300,281.164354,190.930887,109.360137,212.736499,1450.619258
min,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,311.000000,4.000000,1.000000,0.000000,0.000000,1.000000,8.000000
50%,611.500000,25.000000,9.000000,6.000000,3.000000,7.000000,52.000000
75%,3310.250000,108.250000,43.000000,30.250000,17.250000,34.000000,232.500000
max,6020.000000,13031.000000,4742.000000,3644.000000,1860.000000,2789.000000,26066.000000

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1140 entries, 0 to 1139
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     1140 non-null   int64
 1   img_url   1140 non-null   object
 2   prod_url  1140 non-null   object
 3   price     1140 non-null   object
 4   5         1140 non-null   int64
 5   4         1140 non-null   int64
 6   3         1140 non-null   int64
 7   2         1140 non-null   int64
 8   1         1140 non-null   int64
 9   SUM       1140 non-null   int64
dtypes: int64(7), object(3)
memory usage: 89.2+ KB

In [6]:
id = uuid.uuid4()
id.hex

'27090281ab3a4d51ac0ebf5a7150f74f'

In [28]:
id

UUID('8259ca83-c8b8-481a-af1a-1dee90bef995')

In [9]:
prod_id = []
for url in dataset['prod_url']:
    url = url[url.rfind('/')+1:]
    print(url)
    prod_id += [url]

1xiamj
165dfs
1c1wnf
2w7fa4
p0ntc
2du9vd
15qgsz
2diuvh
1sbsct
2breed
25i6iz
epxlp
37mquq
2tym8u
31g8jl
26yjil
u6hd5
33zjt5
2po9mi
105mbl
1uu42k
2bt64q
2jqfw8
2f4kc5
2m0vuc
1j9iz8
1i4b6q
xpuga
2xs130
30d6hy
37jf6j
8d8ha
1rk2qw
163qdn
17uo09
2z7cze
1yql01
1qw2u8
328re9
17neon
18trri
u9jyg
w9k45
345d56
2n73er
zqe9o
207h8a
28i2s8
t6j53
33qbeb
10mrkq
235q39
2dutfj
14g9wh
17td32
13v10w
11w8ry
170kgm
qy6xx
1v05vs
1nm3np
140ij4
s4nz0
1asz9t
1bi4qc
120mm3
2hpf3u
32yuni
11dj9v
13bmkm
1uwu19
2w3gww
a83w9
30e22h
2pzgfx
pp1gx
2q479d
2x4pw6
2dufra
c585d
2c1jke
4mah8
1ugxn1
4l2w8
2dot7a
2xf8te
2ec5ff
1e6c6r
16c32n
1sbme8
wwo5c
2f4lj0
bn7pz
24zlub
2ej0sy
2pvu5t
30o21n
2eypbl
sckqo
26sm3q
2quc43
27omrn
1a9jsg
38vjvb
2bxbic
167on7
77fni
x5ift
2ityzt
busa3
2eroun
1xdlka
25uowx
1jdmat
2j8v1c
369k71
28uudd
2xs0ae
2us6cu
39ijot
28rjwx
1lo4t6
2f854p
2zoqpx
6w8vx
p0mtb
w10oe
19esey
2cdo61
bnnlr
32dn93
2c42pu
16j7sk
30z3f3
390z7l
2pwht3
33uzdp
2bhjqz
2a7z9j
2eqcbv
zgxlp
37dank
16xjkp
1dvsnu
2jy533
33sv6n
2duoay
1o6zdy
u9ock
2m0vhj
2n590v
17n994
30bzdz
2rltnv
153oi9
1x01jd
q3puz
z6ckb
2wgbp0
2awyz8
2uo40c
k87q3
1svqjl
2na3ul
2crzm2
2dv0sd
1s0cju
2ryzxv
119eeb
18h6jj
15uiwy
pasbx
l87eh
98rp7
qvg58
2kag76
1w4uxt
163ui6
2tyy6o
35tw7e
2d83ij
38l9n6
2j59xw
s6wyd
1sl2ob
2dyrwr
2xzwsa
32dqfu
303tke
39amgh
13v23r
1apziq
loyj6
10xxxa
2gxaud
32egju
2xke4x
yoabs
qtl2b
25qp2y
q3gaq
2f387o
32zcw0
2l7r6r
24on01
18o2om
1chhug
32qayg
11oys8
1c18in
2iqqgd
2crwi7
2w7bfo
16j5hv
34i3na
152mwp
2cc9n4
tpaiw
2t1hab
13gyr7
1u274v
12gfg0
19oitu
2smoc
2qthhh
11qk7o
2n6pn6
841lf
2ziw97
fj9w1
30enn4
2uspjh
15u9fz
10abqj
2lurqj
2w5csb
15tluk
21exhl
1sbbu3
2i65kp
2dv49u
19w0cm
1aelut
b1zhe
13zyl1
2o42cn
2boo8f
1j7uah
301prf
28uipr
1a5ee5
33qodt
s33ko
fha7t
2hhnl7
39hnn9
2uodup
swsz
2v5jy9
uu54k
30ysve
2x6s80
2fq1ji
h12zq
379lef
2x8q4b
2m7vcs
2u2pml
t5lmm
1wtvmq
1sber5
1cyb8w
48rzj
37z6s9
6tdsh
1r5kuz
13zv09
2osflh
17z00b
17867h
303lo3
6ywtx
139xi7
2m5xaq
2dbyeu
32vd2e
22wthr
13wtyo
2h7mg6
2pvuk8
2txnum
2yk99q
q9y6f
2v28yo
2gt3ge
2dosbi
1q8e3e
2jpv6z
1sme02
269gof
2g1b0h
2qe6w1
754ly
19231t
yh0m1
1d06qd
197bg1
11j9en
w147t
2qd7ca
33advf
b5dbt
28uiod
bly8l
30eo2m
28jk6y
2c0n6t
g8p4p
1nm2cw
z7ayh
2ek217
5iw79
17nbep
2tinzp
y6pgu
2wi7vm
38lvdy
14mpsg
163rg6
100jt3
2hpem1
36546v
25en2m
2hvqdw
tg4sd
2kfslw
2h7noz
2az25y
9t0nv
1dqeol
wcpg1
hb4iv
2ek54p
39km8k
11w7zk
tyk7c
17nd88
2ecl1e
2dpfna
oqznv
ypg2i
2pvtrh
2qp2zm
10lkdl
2kf8nu
2secm
2obozm
2y5s6u
33qca9
qaol1
197b5o
2dfu4e
2lee8l
2jrcxb
32oyrz
2exrm4
1b7kk9
15tlp3
13xrai
2f1kvk
2epvin
2em9mk
2w596x
ybkkm
2l310k
1xi9a7
2cdagj
39ogl8
2smeja
2e1cm2
23devk
fcpk0
2dqgfa
1btme9
ze031
tyjtp
6w8hj
17uf81
m7h24
342gc6
2bpd91
2dkugj
nxm3n
2m1mmb
1bpl0n
1phtcm
28w02r
30z164
aach1
30eahy
2ypml9
x6fz0
2k6hf1
1n62ij
2vekr1
36ijyj
1zdcai
115x30
2l8ptt
119cko
bvdm3
1ghvso
2nbg7t
2601vb
w0xvb
2cwlu0
18h4wl
1ji195
24op2o
24p9kb
2sw5kl
149mba
bnfds
30ztq5
1pt3bn
2mkyaa
wjkpv
1f46go
2uu9lg
32pv9t
12orh9
2nhpbz
32rpr4
yuceq
18hbk9
38fzvl
2uq7eb
1z8h3a
qaokp
2upv4a
z6lgq
tnxrh
2pn5lf
2n6slf
1bi5c7
393n1z
2nhjys
eud3r
1gu6gq
29sows
2z8jew
2li7yj
29qz6i
2dibdk
orvq5
2ezb47
4lufp
1y3fwq
2nbsl7
2rlfcu
2g6kn0
sil86
2w6che
ykyqi
376xjt
iunbc
13aifa
30ly7y
2k8tnw
14muko
2rcyp7
r26yk
oeb88
2po1u4
36iwy1
18hcvq
2zjbvy
ebay5
1nn11c
4lpn1
2rozww
2wcsi5
10mpl4
19vn16
wxhrp
1j7xvc
2v2djv
18ge73
2kzz5b
16xjyi
10vwto
21473i
ykog6
2sqr8c
w0yh6
sbcn0
388547
167d9b
1413i8
2jj413
2nq6h4
39kx01
1a55b8
1v1p3b
30ksiu
2nq5cd
108skr
yefxk
z7l3y
30d8ml
1v1p5
opzxf
30eb4c
2dv28h
2l78ef
2tys8x
cce4r
p3a1t
u2xfs
19vnai
161a7w
303kfv
2zs4us
31k46k
2pvb06
33451p
11dkgo
cncck
11r9f0
2ngw6g
2n8jz5
2dzypn
2dxx83
32qtx6
jipeb
z32x5
2uzjrd
2l8755
2azpqh
i7nrs
x4hvz
36umtd
32dwci
u66f8
17n7xg
30lx7o
xlhvt
2bohoe
r6q10
16mp4f
302gw4
2075l4
2durim
2n7gpf
2kvnyq
1xjnn5
szqop
2xf27z
39hs18
11eavu
2q5alc
1y2wa6
2fa2oh
2r4sic
1vd6jv
1ol7nj
2q44ib
2zrivf
6r0rs
1xcdgm
r6k52
39cr8l
1yc27u
30lz8p
1ddfk4
37esh5
18gts2
uuoyx
2yr2oo
30s25k
w20s5
2g6nin
92wyj
1b4fdn
36k0k9
2jvgs4
2mhv6e
2r5rlb
2kmb30
247don
2mndut
2w59sj
4ssab
11rnk3
r9ip7
22qk8f
2n0gsg
339ie8
1dzilq
2dze8u
adzoo
13nhk0
37hx8f
2zbjm1
2twl9e
1xvc64
119b3e
2pqq0q
332qqc
1bi64a
2huchd
qy58e
khjnj
2usejs
2xje3y
1xxx5
2d0qrb
24e4bw
2d8iv7
sxagx
1bu7gj
19rwn8
39hst3
2wt1yw
2jzp9e
1v0rpu
2d0eb6
2rxso3
30yrqb
2h059g
1898bl
2v8vj6
bzx60
30eos0
2putb8
ysz9l
30iyzk
13i4v4
ucep8
12xpcq
1n9jrx
2itqpw
112lh6
2lqo5s
20fll
37f7ci
303lgq
2mo454
e5lor
2stkis
2e7chz
1894ie
2w5gel
2n912s
36w9kp
ys8bs
upbka
140m36
2wc683
2h7phh
398ux2
17ihff
2fgauq
2fwrzr
tyjgv
33auqo
1135wr
23klf8
3kp8s
loax6
fthjr
2p199
17mj16
2se7c
14rik3
3350ta
2wa4vf
2nbn6v
2qdu3u
1mr4o4
2rsjo4
2w85tq
2n53jm
2mb0mb
nxs7o
19wc51
te7xc
2oj9ss
1aj9c3
1twgka
uy52l
21s3a5
2n0mvw
1slq06
1qy2jb
1vojou
1l4hy4
2w22b
197mtf
2018ax
z6bns
a4f1s
2x7m28
2h5y8r
2o3pav
1ioz10
2qrvj6
16cil7
2zaey0
117xdt
1le0m
fvf8p
2u1se0
2yzwc3
37ur5w
2dpntp
b1xzi
14qwgw
10nue7
j2yhx
3971m2
398tay
y828w
2zaki4
16j2y6
2dypbk
ozyfc
2uu6dl
19wlfh
f7g99
z5qzi
2p03qd
17j7zw
145uut
15r2qk
26a70i
2vrliu
s4x9k
1418c4
2sx6t7
2975ou
1b4xwk
248qzr
32uyr6
11qkzs
2r3vyj
y6asu
11puol
2stcra
2dbvl2
19oij5
108m4r
rh29x
2x4kug
334zeo
1ol6xn
14wg0d
2gy5bt
s3b6f
39ky6v
yfe7c
2kyysp
31i1qz
10u824
jg68e
xjxdr
qprl0
amjpq
33a59p
osqtm
meqar
tnff9
1fvhp
19pjwv
13bonp
130x6l
18yvuj
r2ah7
122gjs
vx7bv
2zu8dn
2mnpib
2stlgr
2dytzx
2puumk
2yxhbw
34j5t1
237f5j
31g6ox
1tpy7a
2ufzpt
232nzh
2wd1tn
2ueyt2
2l5a4c
2y3ewz
2qvmt5
2qngmx
33vd2i
1rkpa1
2cnuhj
2kit2t
2em48v
2o34w8
16xegb
2v2dr0
nxrj3
167t62
19crei
mfro
197kqf
2ej5tj
25f0sm
qy1g2
2p4n0g
2rll7h
1xw7s1
200plg
2f2hvo
304qhk
2n7o9s
1a7d1d
13hwvg
1h29kw
on0cn
11fb6r
11bxds
88ggw
36jm61
34px5y
2vsaxt
35z7jr
2hutc6
2uf11q
2tjpn8
17j4vg
z3u2o
toxkb
2ca5ur
2dazvn
1a7bps
r1d9h
2eqvjw
46iid
2nexn2
2k9rbm
2x4zlj
2uxh3u
2dgq45
2cbtx6
2cqhcb
to7c4
kzbn2
2bfxrn
xf3a6
2i3n5e
2v6ysk
15d88u
2qe8zt
2l6xi5
17tbjk
108o0m
2twfmk
q5v8j
2ug10s
1yrh0z
zs19v
2zh1wv
2g6njb
20rqs6
17b8en
2yoths
2tyzhi
1zpc4j
2cdldg
2ogwgr
2rcn88
167dzi
2bxtwb
38be5d
2p3s9j
33askk
1zn8jw
22w1mc
rsfc4
u6vny
2gecyk
2i9o0d
16j0nv
12rn0t
2diejb
1i9kxw
2atpqr
30m7no
1wtv2f
hg5az
130gf6
2km804
2b7jns
2nx3b0
2haqyw
22mx91
a3lqd
2ig1iz
35z5a5
1j9xks
2gegf0
14suf7
30ba5w
35g2z8
2d2q18
qxxoj
159i73
34j5sy
5x48w
35huwp
2f0esu
9all9
34xjiw
16je55
2686uy
302g80
ubqnd
pneyc
wxka4
s17lu
3kgg4
gkgv9
5xe1q
15lquu
2bmjpd
2zoqde
2dvofz
1vhcf5
1k2eic
3852ru
2ja44t
171eqe
1v384c
30w3nk
2rl79o
30xufv
2rmrby
17nc0h
fcpkk
2n5d8r
2cxlr3
140jmf
2uynxa
xctbr
2nh13n
33934h
2lfx7d
2nhvve
2rlkzv
2oskfz
2rkfbx
2ydiov
2yfrka
397bb7
1sscnh
397li0
2zwvc8
39oiy3
13b9cs
30jv2b
r1dwv
nfgiz
2yiep1
1a9jkr
1vo8av
p1w5s
9q21x
x0h5s
2oaig8
umvt5
2eed9d
2ek3k7
11qn26
a9kod
4dw3r
14o6dh
s1qkg
24nbaj
2l0jmk
s4nj5
pxgjs
xi67w
17j5cp
dmqq6
150gd6
s09dn
7gsi2
osr1f
qprkt
18xib1
q24zk
sds8c
30zdr6
300o3e
300o3e
37x2yt
36zt87
2f0ar6
2htjpt
2rn1m6
2nmxm0
33837h
30ekfo
393l7f
2mtgbt
2lg267
2dixsb
2be8f8
2tpjf5
36kx0s
1zxg77
2n8s5w
22szkt
2rqvw6
25jn98
112m9y
17ppdi
2tlar4
27hsxn
254bl8
11imat
1qz16a
2u1wr8
2rxf2y
2mgv1
b3a6o
nx5mb
17v6g8
ypgrd
fx7c1
2n2sqx
v5c2n
8h6pr
25v8x2
22slm3
1uu3hc
30ba5r
2czf4w
30eeg2
7gt1e
1vrhak
hcgxi
14satl
2c9b5j
1yo9mj
1xd9ys
9ooun
1aqey4
1276pm
p576a
t9gbd
17egra
9jh9z
163ogy
x02bx
3uk3u
vvz05
oupha
8au4t
ij1ag
136564
15g345
30z5un
38dte9
30bt7t
35e01p
35cifs
2n6ml6
2qp43r
2vw1pd
2tyy6u
2xdu07
2zqq9c
34pcur
30s4jh
38lkkn
2xkc3k
2pxpvu
2jinl8
2m5vwi
2tj8sr
2rbea0
2o3hqr
2wwdvj
20ixje
2vrhss
2uezr9
2pttnc
35gs00
35s0ti
2km9qf
22tahr
2eb91m
2jdibb
2uvdzk
2qe9p5
2g4wup
2tal5y
2swhbs
2f1sv4
2jz0c7
353prz
2hz737
33ks9w
2umnlt
25p1w7
2z8cji
2zrowz
23kppa
2e49kl
2f1wi7
527w8
q2ymh
wqffk
2c2lun
unank
p0rhe
1aatyd
2hd9tm
2cc3es
1v0mm5
1c6q4c
8c0uh
37x27p
1fxx49
17pokf
2n76i8
smfyd
w8ehk
12fesh
113jdg
uzidg
201ubc
2h4ic2

In [10]:
# for i in range(0,180):
#     dataset.loc[i,'prod_url'] = dataset.loc[i,'prod_url'][dataset.loc[i,'prod_url'].rfind('/')+1:]
#     prod_id += [dataset.loc[i,'prod_url']]
len(prod_id)

1140

In [39]:
# l = [dataset['prod_url'] , [prod_id]]
# zip(*l)
# print(l)

[0      1xiamj
1      1wq4nz
2      15qgsz
3      165dfs
4      1vexv5
        ...
175    2li7yg
176    2bd2k0
177     t6j53
178    25qp2y
179     754ly
Name: prod_url, Length: 180, dtype: object, [[<pandas.core.indexing._LocIndexer object at 0x000001D27C613560>, <pandas.core.indexing._LocIndexer object at 0x000001D27C63C540>, '1xiamj', '1wq4nz', '15qgsz', '165dfs', '1vexv5', '1c1wnf', 'p0ntb', '2w7fa4', '2fb25u', '1ya45i', '1sbsct', 'u9jyk', '2diuvh', '2breed', '2du9vd', 'itwca', '2bt64t', 'xs9rd', '33zjt5', '2ussfg', '26yjil', 'u6hd5', 'epxlp', '30d6hw', '37mquq', '345d56', '25i6iz', '1i4b6q', '31g8jl', '105mbl', '8d8ha', '1j9iz8', '1uu42k', '11w8ry', '2b01ni', '170kgm', '18trri', 'xpuga', '2jqfw8', '17td32', '328re8', 'w9k45', '10mrkq', '2z7cze', '12lux0', '16og1q', '17uo09', '1v05vs', '2m0vuc', '28i2s8', 'y7sg9', '2xs130', '17neom', '1bi4qc', '2pzgfy', '235q3c', '2po9mi', '13v10w', '30bzdz', '2tym8u', '2dutfj', '17n994', '2cdo61', '2dyrwr', '14g9wh', '163qdn', '1nm3np', '2q479d', '2xf8te', '1ugxn1', 'eax23', '2dot7a', '1e6c6r', '38vjvb', '390z7l', '2c1jke', 's4nz0', '30o21n', '30e22h', 'qjs2q', 'bn7pz', 'zqe9o', '1uwu19', '24zlub', '1asz9t', 'c585d', '2n90mv', 'a83w9', 'x5ift', '13bmkm', '33qbeb', 'qy6xx', '1cyb2x', '2eqcbv', '32yunj', '2n73er', '2f4lj0', '37jf6j', 'busa3', '4l2w8', '28uudd', '2hpf3u', '2pwht3', '2bhjqz', '2dufra', '27omrn', '1wkdem', '2ec5ff', '2bxbic', '16xjkp', '28rjwx', '153oib', '2ogjks', '21xlz4', '15tluk', 't2yus', '2a7z9j', '120mm3', '1x01jd', '1qw2u9', '2ej0sy', 'zgxlp', '19esey', 'fj9w1', '2jy533', '37dank', '35syqk', 'pp1gx', 'wwo5c', '4mah8', 'loyj6', '33sv6n', '2j8v1c', '1xdlka', '16j7sk', '6w8vx', '2j59xw', '1lo4t6', '2crzm2', '11dj9v', '2rltnv', '77fni', '2l7r6r', '1tdtof', '25uowx', '21exhl', '163ui6', '2mvpr1', '30ly7y', '2c42pu', 'bnnlr', '2ityzt', 'oup6v', '1o6zdy', '2m0vhj', '38uzpk', '2xs0ae', '1phlwm', '2sh0ht', '18h6jj', '1sbme8', '15uiwy', '2n590v', '2l94bm', '13zyl1', '30zubv', '2duoay', '32vo85', '1u274v', 'p0mtb', '1f46gi', '98zjw', '2akdgr', '38l9n6', '1dbf6l', '2li7yg', '2bd2k0', 't6j53', '25qp2y', '754ly']]]

In [11]:
dataset['prod_id'] = prod_id
dataset.to_csv('dataset2.csv' , index = False)

In [12]:
dataset = pd.read_csv('dataset2.csv')
dataset.head()

,index,img_url,prod_url,price,5,4,3,2,1,SUM,prod_id
0,11,https://images.meesho.com/images/products/1167...,https://www.meesho.com/alisha-refined-kurtis/p...,₹293,4613,1864,1622,1104,2248,11451,1xiamj
1,12,https://images.meesho.com/images/products/7079...,https://www.meesho.com/abhisarika-attractive-k...,₹465,4572,2037,1535,968,2379,11491,165dfs
2,13,https://images.meesho.com/images/products/8071...,https://www.meesho.com/kashvi-drishya-kurtis/p...,₹308,13031,4742,3644,1860,2789,26066,1c1wnf
3,14,https://images.meesho.com/images/products/1750...,https://www.meesho.com/chitrarekha-refined-kur...,₹429,765,321,221,117,210,1634,2w7fa4
4,15,https://images.meesho.com/images/products/4202...,https://www.meesho.com/abhisarika-voguish-kurt...,₹583,4130,1900,1243,712,1760,9745,p0ntc

In [60]:
dataset.loc[179]

index                                                     920
img_url     https://images.meesho.com/images/products/1199...
prod_url                                                754ly
price                                                    ₹464
5                                                          12
4                                                           5
3                                                           3
2                                                           2
1                                                           3
SUM                                                        25
prod_id                                                 754ly
Name: 179, dtype: object