In [1]:
import pandas as pd
import numpy as np 
import csv
from csv import writer
import uuid
import random

In [2]:
df = pd.read_csv('dataset2.csv')
df.tail()

,index,img_url,prod_url,price,5,4,3,2,1,SUM,prod_id
1135,6016,https://images.meesho.com/images/products/6454...,https://www.meesho.com/aagam-fashionable-kurti...,₹479,0,0,0,0,0,0,12fesh
1136,6017,https://images.meesho.com/images/products/6231...,https://www.meesho.com/chitrarekha-ensemble-ku...,₹368,5,1,1,1,1,9,113jdg
1137,6018,https://images.meesho.com/images/products/5204...,https://www.meesho.com/aagyeyi-fashionable-kur...,₹533,1,3,0,1,0,5,uzidg
1138,6019,https://images.meesho.com/images/products/1210...,https://www.meesho.com/abhisarika-graceful-kur...,₹565,2,2,5,1,0,10,201ubc
1139,6020,https://images.meesho.com/images/products/1496...,https://www.meesho.com/chitrarekha-pretty-kurt...,₹464,0,0,0,0,0,0,2h4ic2

In [3]:
#generating 1000 users
users = []
for i in range(0,30000):
    users += [uuid.uuid4().hex]
users

['8dce661076864623a54fb83ca5e248d8',
 'c290d7b3b9ce43f19d6962a33c09af6c',
 'f51097f16c68415caa1ab5116c2d4574',
 'f9e95b11cf7c4b2f8cfa1dbef01540e7',
 '9ca5552e734f42d5a06a30c891edd97c',
 'b78f197747754ab992b9cc795804d902',
 'd3421d1dbb6f4e338c7d6267ed788aab',
 'ac7b7069dd714f168a30560f3c2b783d',
 'cb1bf226ccdb415aa9d910055337b044',
 'bc41ae71a4dc494bb02930dc83e4b661',
 '3c348b8d75d845da8ccd92b0941dba38',
 '27f97c2176254cf4845e6993d2a2a08e',
 '73b35e49fe8c4055bdc5489266e270db',
 '6be83c81d3404004bd480fe982f0df62',
 '663dbabb8fe3486e93894f843bbff54e',
 'c0de7199be864e81b907108803937efa',
 '7410845f7cff48d2b27d3224655edd8e',
 '0102d17893a7472ca31a6f6b5d95c577',
 'eee8ea4682f04c0da04e8fcf4aa8cb56',
 'e60198291ad44768955eaa9e89868546',
 '1c3a86842dcc48a3bb9084978c2f5873',
 'bc9cf2d63e39423393ddae3f85701ae4',
 'f3b73a1e428b49ae8e24a7cff3df7a77',
 '2f562015473a4329b7d32486681e1c8f',
 '1758d4e84fef4ce99438cd0caa4c2a6a',
 '33e767338d2d48f0bb6954aa3d1b8fdd',
 'eb2a5ce17c894bc7a7a852068ad58cc9',
 'dffb8b7429d4404da69d1e4399dd2e2f',
 '5635e621f0a14f75938b517473aafa19',
 'abe7cf150c524004a48647ca71c0f2a2',
 'b5cb6f3f904a4275adc71f3021d3c838',
 'd34e2ee5f5774be7ae2e019f391b4e61',
 '273e74c2fcbe41e3a3c2bc2ad3764471',
 '70e27823f1ab47daa130a1d0367f9ca4',
 'fbc0dc91b9cb4658934a8cf27f3fcb60',
 '2ec475bd8bae4704963af77171617bed',
 '3ac09f895d054d018292206460d9c039',
 'c63f9f0eebb64f93b062cb81ffae2e5c',
 'a7c4e70c106244bab0a3a2d378e45250',
 'd0944f6197844cba83eb06b344034fdd',
 '3ae3ee414ca64c909c9d64f83b6b18db',
 '515f969f9a14440d819309de51133eb3',
 'f9d898b2ad414ddaa18f19f211a338af',
 '925460d7e65443eab57bb11e0ea80739',
 '10622271121949668ad86fc02fb3284f',
 '44362c0f63054a0e8f0b7ccd10c33748',
 'ba1528df29c74349a652d2dce264c350',
 '5a438c1c2add4b28945451991918d6ed',
 '368e79d59b9646869a3ba6e7e42b9180',
 '821077c036a5428194a92a2de4aa8cd2',
 '4df5fefa18614d1b8c8e1caca054530a',
 '9fcb829e308242c5ac3049561b6550a6',
 '3a22b04cb279456eac099371313d3a77',
 '5a994b27ec84432896fe5884231764f9',
 'e283f559d8ed4001a7eac282df57b745',
 '99a11bf01caf448999bca605dbe51c95',
 'd63cd84ea9bf438e90e7db2cd578ab28',
 '77e11957199b43a0aa1973a740cb5092',
 'dfa9760c9d1347cfb83819120561b3f2',
 'a46b23d1a76a4ebdb1d14e7ed32e9572',
 '8e410975350b48519acb6e60908a1c93',
 '3e7527e320464a6fa99a00d0bca18c2f',
 '30a12c7946e34301a82725110a1377c0',
 '8a7bc11afaab4551b12f72b930f86672',
 'de8369182154464fb1296c85fc4a1a14',
 '1aa7f03be2f64e8ba6ea4af51cc5f7f8',
 '69a52636070a4346a8db4adc1870c602',
 'b24c960c87284902b7dad9fb8218f4fb',
 '8b2f6ac372494752ba4b723778406af8',
 '27fc37bb0ef840c3b35024a08af07581',
 'f9b9a93e941d404d90d066a3dde64786',
 '4c3bf6d2bed44095b46e10795fd12085',
 '9e1b66cd41364738acfd05d2834b90b6',
 '8fd7838cac1e4dae89ca57474fe8bd4a',
 '654a44b9973b4ffba9434ca997a01a61',
 '5ce5f9c39c7848dd8aaa4cd63fb77c4f',
 '2eba88820bee4954936e91d71eb73af6',
 '5e226bda92214fbf824ce6915483aa16',
 '340d4d2c71b24f7eb71b7a0d394791b0',
 '988cfc1d8a514d70812394ca88eb2722',
 '4cfb5769077748df82a58435a7f25222',
 '113544e201e74293be026755a411935f',
 '588d8de068c84c9cb87955fb4c7816ba',
 '7322b18c9e404aab9752180d2e192213',
 '46ed5fe87d704e71a37112088891631c',
 '1ef1fec462ad4a61bdca8da0255a70d7',
 '53e9c25064ce4f269461a6b8a207a40d',
 '56326c8863094b709a6fe13911b5c5ce',
 'e65b7ee245ad49f3b0e3264b2a9df6aa',
 '8426003fbbcc41669f19eb1b32e67298',
 'f59451711b044d6cb7a9952909da563a',
 'f9a070be1a8648d898550c525cdb1f51',
 'b427a306cbe5431bb73112ca1bb4fb8a',
 '460e4b3037154df587355b648e763cf7',
 '9ed6cfc83f9444759607c6978364439c',
 '7bfd4b86eba8445c93d9b74b98f3f187',
 'ab402a83c128410a944d2ea71964a913',
 'ef8452654de74ffdbc804a0dba18735f',
 '5dcf8feadd9c4f0a8341fa2f533ee217',
 '6b2ddec2cb8441168362bac491f3dd22',
 'd0e5a5800b1a429087f803311b5d12c9',
 '1ffc9de5d6244f8c8e21f12d5265fe02',
 '73824fad118c4930b5588203cca9f387',
 '6af8c1cdfdd144dbb79f59d3c26787f0',
 'ecd015ad6a174fffb6769181eab4d9a6',
 '7ef35e348484429b88b36c6e7706c198',
 '9d3b47c9d9c64a368a3f880400f34fd8',
 '36bda0e946204002b42859c54ff0d297',
 '25e8a4699bbf4a7c9224cae79ae2786e',
 '3e46985766c84da39cf3f9ab870d2ed7',
 '7a361f2238964383982db6133ef2958b',
 '39b2600f7c784a05b5264a3d2d9a9ebe',
 '611b337333484fa6ab1f5413bc4b20a6',
 'fd02ed9a71f749298e26fb61e561d116',
 'f3f044e84562440ea73c13b0425fa982',
 '59db02f9df534dd8ac597c113d97f1a3',
 '1c1c05abf9ee42978b5d8bddf8f60e72',
 '5fc128efa938413cb62618d1cb659ef7',
 '39e4aa5da86144d0a27a7a3ade006844',
 'fc3710803e0c414584b1542d9e465d96',
 '48645c4f8f4f49cbb6d6b73000c617c3',
 '8e0e1a7c834d4c5bb92e1ddb3b6b973a',
 '0479e618746a4ed3bb7ab6aceb48a998',
 '3b40d69e6ba4446bbc240df6a085e889',
 '03b8cb95f9844edfa8bd4b9f453a8d1e',
 'd7ed4ba9a80840838f46066ad83286b9',
 'e706a156eb0742d4936a4fd24216a6d8',
 'fae476b3bbf84103a59cd08ebe49b010',
 '49e2c197dc5f4d25b45db63e0f6c0b98',
 '9b56c91d23524112ab2c74a69ec6c794',
 '157d36a20f8e4ee4a5d90fd2f69c9c0f',
 '2a14e8f58a8e4517aebe71c95cf25daa',
 'ea93d98643bf4a918f381f870227a4cf',
 'c43ccf03c04242eaa335a6e795812a8d',
 'e4a4e015a6e940b0b44510840f09e617',
 '2715ef9c65ba400cb96bd4a3d0b16f6b',
 'b273b3b74b43441dbd602323f7197294',
 '708d89c36c9f4997b42b884a98385870',
 '4d8f3e75a81546d6822323959c2c7a5b',
 '21e7840524d84456b4bd6d585377b9d5',
 '347fa573795a4ac1afd2f39fd2a3ca10',
 'da3463520ccb45209e0d0585d0edae90',
 '7b0af853f42f416db3368c9c75cc3e3a',
 '67e5c49d07c54e47aafffa7a79d05710',
 '2134b2cc12ed47e28f6bfa4ce293f4bd',
 '84820f01e9bb490eb3f1bf13e3d4fa08',
 '89f1893b9fce4a5381e2d628482786aa',
 'c1b53c03a8ba4aa48859f718234cb9a0',
 '2f75702bda7a4f66b23a1fc3418fa1fd',
 '45d642c70a234841a424c4c34ed26a31',
 'caa04b9b96344cb48e35c6a7a81930a8',
 '305c1ef8e2294e4aa1dcf2833692ed14',
 '2b73f50320994a03a96bc0b19d065d37',
 '64bb14dd5612442fb27de7185557a3b9',
 '8a00a4fcc16e418c80a72096b3440e72',
 'a66fe98f4bc14f5dbc0353b7024c71c4',
 'fcac38d79ac44174993a544eb5e0f7e4',
 '4428becb907b4ff4b9173f4fc336f4cb',
 'f619091dc73b4927946c1ea78f2bb6c9',
 '8d36f029f0094744aa95a4c3c6dd024a',
 'cc40392ee76d45f9a711f2256d498360',
 '25ad9163b4d04de684fd24a7d5cf71c3',
 '756f4b77145b41589002d770b4806cce',
 '7ddf266ed993473aa6d2958583de67d0',
 '9b96bfd494034a76bacdd7a00b598ab8',
 '6dede45e6b6b4fe59a7045c86e7e7357',
 '3f87b088339b409a8b4881103f0cc831',
 '5450eae55e614e109cf5cc32128472cb',
 '785fa6c17ff84fa4b18c0f755e45c02a',
 '93cf5302cf30428da5495f5538afd736',
 'f883cbed2b1b4aa1b126691bdd33d9f1',
 '5624cda19f5a4926ace16bd5fa81922a',
 'ec1f434e8cb54b5f8cf22d3bb8e478fe',
 '3319dd42d0174477842d94f1a9912e16',
 '88beb8faa3674eb69b258e461a1ffe27',
 '212b879c68ef45ea85c09cb59ccce605',
 '8110f90bb61941c088f398b8ddf197f2',
 '82821b8b18034d1f825ff76b9cd8d797',
 '262d49fb01da47768f2e3bc6638f0a6b',
 '475749902caf49228024ccc803641832',
 'd009851797d14b48b1ffd720508d2614',
 'a4e038eea6b24133ac7028f32969ba37',
 '634e1e700b3a4800b40e7ec3f33d57c9',
 '04b05eed639f4cec9ef20d78107c5166',
 '45f79f338e1b4ae398ebac875ab1590e',
 '8bba7820c31b484b93ac5e021920e99e',
 '80422297d59d4ed1ae50fdcd75afa8c0',
 'fdfcbbe756b24c7fac95f3e74dcb911b',
 '2dbd089aff0c467db7d3d700ac89d36d',
 'ff8eafa0303649799209c8856b1fe4f2',
 'a537f5a69c634eb4ab1b40f5f87d1daa',
 'd667c79f0cb945d78fc6239957d151e0',
 'd7296e64ef8e4ce89e7f821e6b854493',
 'cb0e79f517974d3895465e4642926831',
 'a02e99eb4bc348c586be38beceda1339',
 'e3f650e22ebf44f780e3446f54e8020b',
 'ae9117d2574848dcaa16624eb5b64d86',
 '1d665f12e6754a249298ad11392496b6',
 'c05f33fa847d43708fbebb02a6b066ce',
 'a779f44c576248b0b64f1990ddb4eb5c',
 'f77c2de2b4354bf5ae98f868f06a3a9c',
 '5b651e74f7f74d2b9427cec7d84d9d33',
 '7af72d50435c4f8da07cfe0ef84ff47a',
 '0f292f9607f7461ebac6843a7f326008',
 '41483793640c4909b2025953ad7a43db',
 '75c9c27f237a4ec3a25db6f0dbcf0303',
 'e8d9763f7242451f99f3610f2c560168',
 '002d22886af649b3b29a2379aac7bbe3',
 '388dba3522414a3093d7fea2d7a6eaca',
 '19625ac41c4c42f89fb82e67deb27eb8',
 '963118bb15524bc085542d9144803644',
 'dfa1cf300d584b90800ccf6135757ece',
 'cbd4d8d462f54ea0abdfb1ca05cc2121',
 '38373b9958054e34a8e365d084ccba5e',
 '82e69950703744f892e680074a973fb6',
 '067edbdb9e044ba886c2bd8537b18c6e',
 'aae3d11869e94c59a2f233d1ebe607e7',
 'bc20a26d57e64e6dbb73e5a0c14b5bc7',
 'b5394fd70d99441ba720c5240e0a4a0a',
 'b3b1e7b956fd4d08bf840fae722fab76',
 'e22ef84f4c7441709817aa6b090ede27',
 'b96d1dc1ab374760aa872f020773218f',
 '494ce657ad8e4a7a9ac5ba80299da0d3',
 '44cb92c6290a455ca26399e931134973',
 '46e1226fc57a41e2b3ff687ed616e7b1',
 'e0fc4ebbda864557b8d1a8c494563bc3',
 '1d7445b70ad249feb6b85d753376847c',
 'ffc8e715be874d7682320702ea195191',
 '9bbc6335ec0943b9a4b47a67a760706b',
 '07d4fe209d9a434dbac42a72b0fcbec6',
 'bac0d5af812c48d295cd17070aabe7ae',
 'ea7838cccc5c4e91a87386c4de967298',
 '801ef9554a724fe094d4bbdfa909273f',
 'b5603bf82e654faf90267f407eca7398',
 'eefd7ae6b1024403a65b7f0ecbb6b4ca',
 'f00bb6934f67441c85cf51d3700a63e9',
 '5393fd161aff41ff87ace92c967d6de6',
 '2ecbcd0f7b9a41a59ff2e4dcc60f3284',
 '9477954a3e8e4aa485a2a79536fc7a4a',
 '99bd716abb19457f88776a7f56021b2c',
 '21cf259292b249ec940e91ea7c2d3282',
 '2f03d465e65d43f5b280673acbbc88b6',
 'f082d3f2f2644c0cad6b0e46d1d22b93',
 '0fd32a3c7c3e46a795431cbc1706af1a',
 'eb4ab56f7b6a46a6ae3af20716334488',
 'e07ba22c05734610886464b3c5125aed',
 'd397e7ce88af4286898d0b0f8313b0dd',
 '8c0f1c99f410444b8dad3c2f4ffb07a5',
 'b29e98fa02fa4ef0910a1c761ec70453',
 '73e0aca775e641fe8d6c7c7612dcade7',
 '549b071077d547d791f1809f08c1a307',
 '1176eb39acf343baa67efb0787fff230',
 '3bc35fd877434509b8659491e6a9920d',
 '4b8a898925cb440ab1df088bc41a9325',
 'a135e4b6086240eb9b5e9175d7ac80ba',
 '30bb4802b9374dc381458dd3cb5321fd',
 '4443e91b3e8840e88131a84f2b508f30',
 'f6ab4a439dcd49c8ba6d7ad8fe379ace',
 'f9a3981fe05641b7ac39e32ce5124a8b',
 '0b1ec52c6a2d43bdafb7698500f727b9',
 '89665bce73d74719bb7b6753e036ae3b',
 '7954dbfa9bff464291cafdef379f02fa',
 '401b3fe6129c4470b0290eeab95f6b03',
 '215053d4c46f425ba8fbf47d69a4da9c',
 'b503018ff29345ab889705a4b1f44998',
 '47ac7846af3f4b8eb3d55a4518b9bd44',
 'db48a9c829b7499892ae006fb804a6cb',
 '8d2798b1b80a44efa949a885fc6eb665',
 '81cdbfce11e9475aab9863a97c404579',
 'e85d06e1b56c43f7b5328bc11ad63cb2',
 'abe64e6ecceb4479a121e4791f9569e7',
 'abc3c33efea74b8da1451cee25bc20ce',
 '9a536912d5bd4459955bcf0859ae8647',
 'cca33e3629cc4d9bb1ce546be55bc8d7',
 '2135080136234247b3ee06e0d8ca500e',
 '58d622ad3f7149859fa827b8d18f8021',
 'f88be65bb5c14f4b9f4db2d37b793d73',
 '5c5e96c00320423d92ab43741638c927',
 '46c0eb72994348ba9ba058ee04e03f09',
 '9c9aa4ec54e0437fa588714caa756b7d',
 'e3f9ff7435754d63b119cd1be364b9cb',
 '6822429a971943ecb6314c82f967a311',
 'ab24e440d2ce4e00b3499f09eff0c0e8',
 '0f7cfa2222094ecfaea23f9c6e957b6e',
 'ff074c5e9fb94ad98216b7faa5978a11',
 'c65e26608ef64c8489bd2cf3e6f44b0e',
 'a0f5406db0db46868f89f762e0dee70f',
 'f8f95311c65b4c2ea1ea56663cbc7444',
 '22557ed5f2dd4e468fcd0d14cb86c6eb',
 '514ac7b9de694cbb8c2fda879227b1bf',
 '7b964b35d6a74fa38b9d82c52c1e21c9',
 '6d61595112fd48b6a2ed692c4db0a236',
 '78339e89731c475db8776619594ca837',
 'bb78487e160742f68e9dfaeedacd8924',
 '8116eebce56141f6af723304ee98aae4',
 '48cbcaa789924da6811e35ffac87112e',
 '3c4dced4e71b49deb02ed2157cacafe9',
 '043bb6f967ba477b8e4de2cff1847c6c',
 '8ad2e26705344dc2b6062505a3e2d425',
 '022fe05cfd9d4812ab8e4d12b8322053',
 '1fa7f0eacfbe48dc9b0b5b134e29f698',
 'c99ba9a3eb604be19b7ba9d21bdde81a',
 'f03597ce3f8946a3ab95ce41d3667425',
 'ace416969def47039df737f4aa74ef2c',
 '7d6328f993ab46df902a896c4b2ee204',
 'b219c8c16e294989840ab05cc722394c',
 'e253afdf969645289b1d0bc8df3527f9',
 'a3777b9c47484af4bdb488c1e3a4d393',
 'a3075c863efb458d942e834578431c68',
 '5f91723fc0384fcbb46cd06e25628a70',
 '6891c807b8e34a7ba1654b550034c3d5',
 'f7732164fc8f426683cb14237456c6fd',
 'c71ccdcf224f44e68258b83d28c5288c',
 '40e80a80bc75443aaa79ebbbbbe74802',
 '4977ee17791e4b888f95bd626ca28af7',
 'b7b70218407c41bb8b710a563b919659',
 'ce8516995195458687c703aae60f8040',
 'fda0f637004b4522adefa573acf2b5df',
 '1623fe7e6a774be9afc2bdf5e7e3e162',
 'd338b323000f45458be09d529d2ac961',
 '690413da25254e37ab2944561ce8b557',
 '66c9c312c614456f929f64d8a99c250a',
 '3b6cdf39116a4aee9cce7df390503570',
 '6d1879ab5f444fa49257073ce7e313a3',
 '6387ce6505d74cdfa346905e03b807f7',
 '6a193ddb428f4f40ae2b5a05f4c9f7de',
 '84f239a36d22486791e1e3aaa2d1a126',
 '6a737bb64f1a44108c988b17be700d4a',
 '71b393d0967e4a7289e09c261aad5a33',
 '744987cdbbf246d0a386ea466d407dd6',
 'd037f03392694140b21afc466880a134',
 'ce175dc2dd56446fbd439bee5ab814a8',
 'ec5c666b933943759ed4cf5e6aa44027',
 '58d42083c33545cea1d777d617873c35',
 'bcca7a516f1040218c8a7df900cfee60',
 '38d505f15f9d4853add40b31fd3b31af',
 'd51bd434017b44c18c9d2128c544550e',
 '475b027ec32a4b1db76e9dacf15e6e18',
 '5f75b61d971a41889a686d3da18a01d4',
 'b859623932444103bd9bc1e1a7ef6a93',
 'e9eb2a6865114da6a0b3811f4141b5bb',
 'd67d94317f9944ec93b37feb5ddb892a',
 '1ce0847593254e2e97bb264c82d00439',
 'ef08a4baefee4ea38ce029f876d8424e',
 '976c830d2fbc486ea9629efd14c0a81a',
 '6cb8d1718e5d4b03b48afd9877c30135',
 '47f874066eaa43be85b0277d13f9bced',
 'bcd49d9eca854dc5b494beaa0aea748c',
 '155af4bf082c40e68201f1b100e327c5',
 'b9f2fb943d4f44c0b79c456e9e003cb6',
 '0dea0ffcb6e540e29cb586d225b8ea83',
 'ee903eb13013453eb2dd5a1f38df6e13',
 'e9f9e3139950493da0a39d63380e24fd',
 'bf568f92a9504a9e821f88a2ce7c546c',
 'af4ca501b85c4965882ff9b44e1f9ef4',
 '35c4a2abf3954ebbb216cfd917f5089c',
 '839ed89fe60b4d7299e3a786e7d30d3f',
 '1a4bc69258cd457da74029e223b1d1a0',
 'f926deb861ed44dfb7a16ea607e0c8df',
 'f49fe431f9ad4593bc5356a346ac6861',
 '253b589bc6eb47989ed610a18e79f122',
 '8e495139565f4063a62995339bd96494',
 'ad53b7e3d2c4476e8b2bc9743c784550',
 '7eacb15d01bc4252b6ac5f1614aab24f',
 'c880e24e831f406ba5202424ca31b3a6',
 '585ccd11517b4cd9b2fa127f9048f523',
 'c8b3f235da244bfcb9f5276dd994df2c',
 'b0449979fdee498f97a9579fe5088c51',
 'a74f233c55cb48eeb2b35f7e14735c04',
 '9d84231edb17462eb566d39b1055835b',
 'eadf92dc01d748569de2a0e2f2a674e2',
 'edf7fa58d3884554b0f989e51c2e658f',
 'bfc0990cfc114a978276404300097222',
 '21aeedbf97634a8085fa59698e2d3485',
 '870710735d5e42a195dd3a78e47834de',
 'e3e39735e18b4cf2959d2f9fc39e4820',
 'f2497a46ced44309844141b5d4e66adb',
 'fefff98064ad4f689394df7065254c56',
 '56d3de64edc341f39b106f8fb14f8753',
 '64643d7bde1d45e9bd1829d89f36da13',
 'f3f212baca064989902437e0d5ce6935',
 '1accc5e1d9764d9eaa95d7f72cd7c0da',
 'd6a3248cfaaa4695b23fe59d3a7059e0',
 '15e0a154ab264d8aa357b73b9c821fac',
 '701003d6008147fd8f753d3c2e78b3bb',
 'c4e3aa7e5cfa47dea195b494c31eaf5c',
 '6f4bb0ad468743899b00830c43e657af',
 'fed3b54e7d1d41f0bd6d1908e2f98904',
 'c66aa1f5eb6e4a4faf5a7c53e2a7bfcf',
 '00729a3f865f4814b6435664336d1442',
 'fe7705a4445446f79c050b772263fdd0',
 '02cb28c78d214ec2a24916f584f6f69d',
 '113b2111f7c247e3927f337d27b6ecf7',
 '54535595d3684e08a97049ef5c61a389',
 '39d34a3ceda2454f9780073c81f7ef02',
 'bdd76202346f4b299f12733ed6b5300a',
 'f2b85822a34348c1b559aa4359aadfbf',
 'f63862655fce40bd90a27a302c82372d',
 '74ac6aeffe7b423884ed7b952da2bc8d',
 'e4990f69c3cf4bd4aa3789c89ce5c992',
 '83729c37c8a14720bcc35369be0d8909',
 'd118604a99654cfba5a5d72bb44e60e5',
 'aa193f3078b84ae3b9857c66f7910038',
 'c95ec69824864163b0d6798efba1b2d8',
 '54e427af531d4a8abbda26fd48d45a65',
 '57b9264d229c4fe9ba687a7c4967ff53',
 'e7995e768f304f60a042fd24a8c5e5d5',
 '55f81bff118f4941ac4cfd9fcdd301ea',
 'fd4fa17b4ea14bfa9a66d8517646c799',
 '10bd4888faf44ca08d9aec158f68af1a',
 '20fa512e1a924e45a262da89918beb1e',
 'e699aa6bb9b249ac98e53ce43cf1ef9a',
 '25b16410d13d426a9354a1bbc0222702',
 '3c77ddd245344dea9bfe9bc9c82e5342',
 'bae88c19bfad457596dc96f74803afc0',
 '519bf47f58374440ba98159c55db812f',
 '880e6512badb44cf9f66d3ec66170453',
 '9b5bd4a32eea41f2a67cdc12bf610b55',
 'd4f16376d0d54826af2b7c488ef1ffec',
 '9c73387203b94267adaa39a6401aab97',
 '4e2b7d79d6dc482994d22239081c7e61',
 '7636268f154f447a85587cb187cfef11',
 '131a244a574a4992bc67f76f2f56fb9e',
 '4357d05a0c554ee7b5f4b7b95d4359c5',
 'fe5dd8ce1c8b4d309d536d8dafe7fd03',
 'd94cc9c52beb4380a9111271ba672ca6',
 '383ecf12d39945c1aa97326e63b2faf1',
 'b9012d8d825643a99c0bd95b0e6bffb6',
 '1f4e0d3d6ff14773969cebfd9c2abd67',
 '77177201b9324278a81e05a9c957e721',
 'cc6cef96c4094f18bf64dbd87099b052',
 '64d4e85c91614d02a6bd716e6e3eaa0b',
 '1970b8bb316c43b4a5bf7ff10fc2f7ff',
 '4dd46846b5f14526ab159992a2da134a',
 '4a01303705fb45acaf65642c0df5bb2a',
 'd9b1746e94e340d4839b031c7611b7eb',
 '0609cf5f1de2474a952bc60edacadb9f',
 '87ffc17095fa4b0a9b62efc24e9357f4',
 'fda817c4398e4aa4bf5faee3b64ef87a',
 '1e17ad7e29414aa796504d9890a84688',
 '211ca93f99c8407f87f1659518ab02b8',
 'ad7f2558d4994f14b9c552d0e8472bcf',
 '417c6e1b2d3b4ee3b4386e68f204befd',
 '104a788039074f0d9ae82c18426b9d46',
 '9ffaa28f742741faabbcda0c228f42ed',
 '6f6601929ce44425b6cff9a7bbeeb845',
 'f070969ec7254f578d2790f7f685389b',
 'c221c428ef4e428d89c70293b2640e0a',
 '8f8327bc262e42b2988c578de3d4f550',
 '2ba9d9ec21c84f2d83aa27857b02c967',
 'e0a84b43f78a4901afa587eb07b8f62c',
 '455199be09cb48149fe38fce8fa782dd',
 'c64d7f93d84b4e66999798f869932d07',
 '5563239b4ea444b2aa5964a6ec95d878',
 'd651c2ea94d4471ea03f851dd3e0f607',
 'b9891e57d7b04294b8a96bc731fa6aa4',
 '3fec2a015dbb4f66b04d73647374a0da',
 '9fe1d6fffcda4c679bdca610dc58248b',
 'b8f66d4e5a7d4f2898d6f2b7f69791d8',
 'ccb561a4800f418dad9c6d0a2e6ba03a',
 'f4fba9fcce394728af0edc28fa1d32ec',
 '357381bd3c984358b13289e8d32e48c6',
 'cf34fea67fe84b7b9dd3757a7143ed4d',
 'cb76b24230d5449d886d9f2c3e673285',
 '1fd8f959abcc480790d91ae7aa51c90d',
 '2b25f96c42764e2d84a2150829b71030',
 '0380afc13d37496c80b730f10505256b',
 '9d4beedc64a64452bbc194fa35efbeae',
 'a78410ad55614d61b72e868d022cec15',
 '50ccb9a3cd72432d9d129d804dc8569e',
 'b9dbec0170b14265b6dd4318565c43c2',
 'c4cbfb6290a246b8b24bbd6c65333473',
 'ac8014e0df614b4daba10a504e75b203',
 'a2f81e6c4f56436c81443c558a619ec5',
 '3a410929c1c742e6bbc03c1dc8c5c099',
 '100cd44368e04630b1561ba163857d56',
 'cba1500518cb48f4af1d3ce1da2566c4',
 '6da2935e9b984cde9ad82357f3255bca',
 'e41c83fedfd1425e91cb2de48967acc2',
 'fa94d626141c44bea860a8c152d63cd7',
 'f53edb2d864e4addac801eaeac64367f',
 'b53ba7cc7ed04e71ad77a921fbbcc331',
 'adc00fc339d746979a2298b25d41fab4',
 'e672ab6d16284f038063e81c48c47789',
 '004bfc982ad5438ab0c4c98ad6c90df9',
 '3220522b95cb47de90001cd7300e6282',
 '89711f35e40e4fd4aa4db758651a831c',
 '26e9ed2967554c6a80ecc235e029811c',
 '4f1ed881a8d44ccc92b333be362b5fab',
 'de24ab353a81404da4fa792e9f4c33ba',
 '6b8501112f0f4115912e15062b39c425',
 '3ceff7eafe734a8a9fdcbf1e05ddfbd1',
 'cc9e6f6db1c6488cbf7e89433daabf49',
 '94da4357067d4f98aaa38eb15b7a9c04',
 'd966bba9f6964eaaa2f70370cf29d412',
 '56c4af99a85148caab193bcd08c76ab4',
 '440351dd51f74119a1086f280101a04e',
 '539ccd3189a54006aaec0d05ae746fd7',
 'bb3e94c319534a179b10985747649d79',
 '59a800a17ab9478499331f5c0d497069',
 '3c0de2c00ac1409f811adf203c7d1142',
 '80fc8043604543e78e77bddf2fdaa6bf',
 'b298be8b66d34f4fa8bef4066c222199',
 '474f2ed645744113b28382502cf8daad',
 'a82069e996634330aa36a74ca613d8e0',
 '591ca8b871b6418d929201fb782548e7',
 '77feb70ba3674f6aae7f0c1d47a44df4',
 '9c29528e0660445fb413cf876be9100b',
 'f540372de3764470b9bbcae9fc8aa4b2',
 '1eb562103603426a88dd794a91b5e8e8',
 '1c344bfe134b497fbba5ca9ae07f94bf',
 'ffd66efbfb274ba98f38995a890585c5',
 'f88dd5fde7884b24af8f595f9300d6a8',
 '6b4fe514b8484cad8d253253b6feae0d',
 'b42675878db043e7a4b4509be3a8fcc3',
 '1ddb7cd46da9428a9adf3ff215711bf6',
 'e2ae4fd971824916a37896c58066c4d6',
 'b4a6a62cb6204c8f91cee67d2ec7d21c',
 'b07f81526b5f4c258b287626bf41cb55',
 '03e216d089b14528a199272039fbb4dd',
 'b0e39e0e3000435c96ca0334c4b325b9',
 'f9e4a127db5d48c38d801f4cd5337838',
 '73ba423bc8334a9b97f0f4a8fd0a952d',
 '876964d398854f8ba4bbef818822ae85',
 '35509a1bb8f1468ab3778073927418b0',
 'efcfa546aea04872bc5be18ed15a9c19',
 '9bdb9d93d0994f718434a9341d5a6750',
 '4664b086d3cc4a08a4bcd8c684e7cb3c',
 '8ec831ffa04049ae95e92b9a4644d414',
 '01055494bb4a4a3fbb90d519a7c02f09',
 '21b08614136042bfa9fd1f1fbd6ed8b0',
 '815eae25055d440b99f3fe112ece0df8',
 '287de406d7364bc58f3a2238dc077c05',
 'c8476731dfe44bdfab9b601a9466fac7',
 '268c7c78fdf241a3a282496d377ec493',
 '7207ac41f54543bda1120badce0349a0',
 '48ba524d0dbd4754b62d749671ebaec9',
 '65f2fcb82eeb44119b5e81ce2540b6a1',
 '642ae11e7dfb47a5988cb0f99e42df6c',
 'd5c179117e3b4cc78d26b2c0d8763821',

In [5]:
users[29999]

'23f88c03f96641e2a3a9c5b1cf52f2fb'

In [6]:
random.randint(1000000000 , 2000000000)

1410669421

In [15]:
df.loc[0]['5']

166

In [14]:
with open('kurtiData.csv', 'w' , encoding = 'utf-8' , newline='') as f:
    write = csv.writer(f)
    parameters = ['user_id' , 'product_id' ,'product_url', 'image_url', 'price' , 'rating' , 'timestamp']
    write.writerow(parameters)
    for i in range(0,1140):
        temp = set([])
        for j in range(0,df.loc[i]['5']):
            index = random.randint(0,29999)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                product_url=df.loc[i]['prod_url']
                image_url=df.loc[i]['img_url']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 5
                l5 = [user , product ,product_url, image_url, price , rating , timestamp]
                write.writerow(l5)
            else : continue
                
        for j in range(0,df.loc[i]['4']):
            index = random.randint(0,29999)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                product_url=df.loc[i]['prod_url']
                image_url=df.loc[i]['img_url']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 4
                l4 = [user , product ,product_url, image_url, price , rating , timestamp]
                write.writerow(l4)
            else : continue
        
        for j in range(0,df.loc[i]['3']):
            index = random.randint(0,29999)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                product_url=df.loc[i]['prod_url']
                image_url=df.loc[i]['img_url']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 3
                l3 = [user , product ,product_url, image_url, price , rating , timestamp]
                write.writerow(l3)
            else : continue
                
        for j in range(0,df.loc[i]['2']):
            index = random.randint(0,29999)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                product_url=df.loc[i]['prod_url']
                image_url=df.loc[i]['img_url']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 2
                l2 = [user , product ,product_url, image_url, price , rating , timestamp]
                write.writerow(l2)
            else : continue
                
                
        for j in range(0,df.loc[i]['1']):
            index = random.randint(0,29999)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                product_url=df.loc[i]['prod_url']
                image_url=df.loc[i]['img_url']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 1
                l1 = [user , product ,product_url, image_url, price , rating , timestamp]
                write.writerow(l1)
            else : continue

In [15]:
dataset = pd.read_csv('kurtiData.csv')
dataset.head()

,user_id,product_id,product_url,image_url,price,rating,timestamp
0,0b32cb93b4d1467a895fdd0c0fdcac7d,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1816526580
1,a546c81dcb9346619c00f3632bb39318,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1431790209
2,6f7480ff712d42eb9be53f37641a3bf9,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1455698017
3,cf05abc75bd74b159bc91a76ad4bfbb5,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1419335880
4,893a87b0ef41435cbd40f5065bdff448,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1195975318

In [ ]:
# for i in range(0 , 12762):
#     dataset.loc[i][price] = dataset.loc[i]['price'].replace('₹','')