In [2]:
import pandas as pd
import numpy as np 
import csv
from csv import writer
import uuid
import random

In [18]:
df = pd.read_csv('dataset2.csv')
df.tail()

,index,img_url,prod_url,price,5,4,3,2,1,SUM,prod_id
175,916,https://images.meesho.com/images/products/1570...,https://www.meesho.com/adrika-voguish-kurtis/p...,₹503,7,3,3,2,3,18,2li7yg
176,917,https://images.meesho.com/images/products/1400...,https://www.meesho.com/trendy-fashionable-kurt...,₹434,15,6,3,1,3,28,2bd2k0
177,918,https://images.meesho.com/images/products/4901...,https://www.meesho.com/adrika-petite-kurtis/p/...,₹261,2,1,1,1,1,6,t6j53
178,919,https://images.meesho.com/images/products/1305...,https://www.meesho.com/aagyeyi-petite-kurtis/p...,₹478,1,1,0,1,0,3,25qp2y
179,920,https://images.meesho.com/images/products/1199...,https://www.meesho.com/womens-rayon-chikankari...,₹464,12,5,3,2,3,25,754ly

In [4]:
#generating 1000 users
users = []
for i in range(0,1500):
    users += [uuid.uuid4().hex]
users

['125a766427aa437081de8df94b4e7545',
 '9e34d032305c48948ea3c55b93fdde75',
 '06da9600f9184544b76bc2a466594ec7',
 '7bbd43e8cf70495ea99ba1b41cc30023',
 '5ead279837594840a0b5e1aa8669a96f',
 '21cc7ada7a334af0add279eedf176efb',
 '011380f6cf5b443486cd3b49e72b1110',
 '132edc2b0a324a28aae94b3b298590ee',
 'f75a105c47da4b0cb04e528659f141fd',
 '2c30c9acb12646e0b98bd7608f40ba13',
 'baf500be18ad4ba6ae76981d3e3416e8',
 'd8b90d7f4441469caca3d56c679c9823',
 '1ce8ae9526024f2cae325c6fed69fec8',
 '29cf1165c5ae449998df1243178a37ce',
 '772215a344a54d91a33cc0c9f60bc4e5',
 '952dd2d6a0d1428f8c26dc6d3a8234ce',
 'ae0aa231efb9468b9bcc50f88042dc2a',
 '8af97688aa7348caa7731349e957705b',
 '6d7a47aa490a4317a58ea35d63712469',
 '5b98c51c4c294648a50955b11efff5dc',
 'eb48c44af2e54c97ba8f202555677dac',
 'fbadc3d9fbfa4ae0a85fe835dd767f82',
 '5274e467e14947b296eaf6b1528b2fb8',
 'aafae04ff1524077b4a42fbe58ff7fae',
 '2760d8675f864dd6b4d282f6edcaaf7e',
 '6cf1d3deb7644ce0a372942e37b118dd',
 '186c3303ddf9478cba07f9ee8e480ed7',
 '2a4a914fdf5f402c9c9649a04f65b950',
 'e0ff9761594d4f75b1e2bfe7e23e3835',
 '18ebf34b2bcc4727be0b93e6002fef08',
 'dd01d8e1e53648c7ae7df077c550b224',
 '68befdad601d4f6895df9fcc376a7430',
 'a3bcb99d3bb346ddbb78adb8bc5b33ec',
 '9914a5897e104a0b9dafce2e071b65e1',
 'b537d8207f43495781d8a9168e2a9ad0',
 '56cb417302b840e3b32eab5c8db26597',
 '41369e44dced47cba2b652fc6a42c71d',
 '9e16e6f026f6436caca940ae43059fc5',
 'b2ab0913556e449db12688869a095f8c',
 '645dcfdfee9d4bcc85db5fa3b391f9a4',
 'b31fabe6ca8b41f18f5019fc6d920d12',
 '2bd99cc2e8294603a8e574835ef5dee9',
 'dc9f207910b34033a1433c34a6eec8a0',
 '44f4bec2fbca491eb38cdd72cb5bdabc',
 'ef3cabc90b444472a102031ecfbd3ced',
 '5b03b195d1824d5283074c2a682cacd1',
 '4ea67290b7fc4d6eb9c178cdc6c376d3',
 '83310db5fc08404aa8e1c3f0326cfee0',
 '064b3ac4c3f94f3aa88300aa7e32b0e2',
 '1abd589b8bdf403fae41c5d261d87723',
 'ccb903a07a4f4954be188a5efb0be148',
 '209fd45c4dd84ad6913fdf763caeb0df',
 '5d2422be1032432ba73ce5b1c37bcede',
 '724ba373953b4c3f934e48e44e6e5218',
 '41abf49c47ea44b68d44b80e4013b363',
 '39d1e81b6a6d477da63cdef61c7d1138',
 '5b3dabd5180a485f8079e4f853c81e96',
 'b49d92d644cd43099eb9b27426945956',
 '44caf828d54d40628da5d09f9336e0a0',
 'c41ac835533b43e4ad7b019c7ffab4cd',
 'd94799e81f1845a398fcdeeb1ee99f97',
 '515e8cd05b9d47e49d13212acc1bb029',
 '185ff6f9526a4cd781a9297a1bace15b',
 '43a44964f6d44306a7808ef4f152f8f6',
 'f7dce021c66243f4a082942d0a1453df',
 'a01604687a214d59a8646d6c60647106',
 '67155acc163743329319ac78b27761c9',
 'c862aad12d80461795a8eebf276dd43c',
 '4e7e5086b7e742ecafaaefd080ca1a4b',
 '63f30b1f73b341a787a438a99368ff76',
 'e23c3af9a3c64149ac543600634dd680',
 '59a314ca80db46de85ab9f5d11d1cd4e',
 '6a423c95b9674baf84061540ed035c61',
 '9035dd542f9244d395efbbbe1d823a8a',
 '9735a7f32623482baf2b6700b1ab30ca',
 'b9eb7a55fdc34a27b21dbc5c328fbed3',
 '6eaf1142d58440e79e4481d5a88f050b',
 '086b9ceea27f43dfb254ace4ba587735',
 '6b0134dc37d046839f926fca03a9bdf4',
 'eb2d12cf1b5b4cea982e11acf655b726',
 '643e1531b77140c0950657af5859ca9b',
 '6cf29219341941e490f9fa818059aa77',
 'f98fe21474aa47ad971229351cc6f644',
 'd17f04a8bf4145a3995e900118c8d20e',
 '7ec965e6785e4271824051239279d59c',
 'e4930788574740e28b0aedd75879f894',
 'b85e69a437604830816548beb3db0998',
 'aaab0aacda494798a9afb83a1e19f38f',
 '98590532cf244c989c5ce83581d68d01',
 'd41a8ce82c5349bb997097989f58327b',
 'ae2ed0f739e94e498330860a996bce6b',
 'a7f1dc3c56144d4b9973c7fbc7d7db1d',
 'ab2eb0a28422438a94838b01482e1901',
 '68b79c54254245119aaa6603b3f032f6',
 'c9208b71283b452d8b32f491bcc2346e',
 '67d7e2c3c1c84b2189e1708150d0a607',
 '619cdba157d74fc18dd3456f915cd428',
 '87720e5db94e4304bb2fd38a221ec8da',
 '13466373fe564f558c1e6efb69d01b5f',
 '586a0196d2d741639614fe2e624a733f',
 'c39fcd052e1847ef8e71b26fd6bd9e12',
 'a0194525f449485da404404ff8e9d035',
 '5dd4bfd43a1f4e15aeeaba85c9d3c09e',
 '9b796a1a5f54414ab4b42f7fbf6e6f98',
 '7daf0636b00b4c04ab56b57febaecb76',
 '5b696d509c0a47868e238945581d2340',
 '8eb46931f58a45518a3658c47c2648d7',
 'c6795c545602465f9cf3664bee3e0797',
 '0c00dc8336464a368ae26960bc55b13e',
 'c9967103e8754196b5471da299855d44',
 'acf086d0119c4aa3a1bd9a3c14914e3a',
 'e567a3056c1d428884384dae4f5773e8',
 'dc432b9bb59d413192fe3fd6408639b8',
 '1909fff10c564ad795db606d78c53909',
 'e32679bb6dc44f9c90b1066dd63de1d3',
 'b4af60eb4b2f488da738f170ce7ef919',
 '845426c7185c456da3a6acefe889be57',
 '6a322115fd8b409f98a98706c43066f8',
 'a50b05e7f990404e86fbeea18ddf7229',
 'ed0df4f10964447b86914240abc7d532',
 '9716054f6df5450ab73da6f61d546f95',
 'e0871a90cb6f4e1aaacce8b5ef5055f4',
 '94ab08380cae4a618783848a572dbd9e',
 '79619ed3a8fe4615aa48db0b09c7e606',
 '6dd091f6511b429786b5971b3cbdef09',
 '1b6e62857afd427eb293e9788d4aa845',
 '26679732bb344d4fbac65200ff51e391',
 'a95587d409954c0081e6a820fc520d61',
 '5d07775332054c40bad2e888903c0efd',
 '672a7b0722954df58531444f1f5b31da',
 '66f1159edcf4440eb7d984df1c616153',
 'bb07f7728faf48e7be8fa220f0645119',
 'fad4894a11244dfaa1b32bfca0e7ce68',
 'b9ce78c65a304d4a9fe3ebde956ef26c',
 'fd6168633233498eb58caa63a7cd44af',
 '47e6a123b8e04a9087298004e6443aba',
 'b091e828311d43e98815c53675dbf521',
 '613a18be6b0f4a44989e6f0af33c285a',
 '5ce73670da034f8daf9522bf2e6e0418',
 'a1e83023e5644a988df680f843fea980',
 '33cf21c14178432bb485f672ec6406e0',
 'ce54641bc84e4154a1b7a59e70872562',
 '2d89e04914254db6b429506245bef58c',
 'b882f986948b4e54adda7ba60dcfc756',
 'dc8f39c9d2704c659f2abd12095978cd',
 'bfe58c348d6947e195978f410307f52f',
 'a3743221d9a74d7ca028b4460009c9b1',
 '07720d4cd85f4629bb262117258558d1',
 '9dcb136770b548b58102c5384f6403a6',
 '6f47b2ff8daa4e97bff1a01fdf0c21b2',
 'e904e265df7849e496e06ab527821e3f',
 'ead9cf08144e44058e79997a37cf3a6f',
 '56790519e9874bd19965eb23a86b1d73',
 'a06ac004623b492cbd0fc46130bc5e60',
 '2621b71fd4d9492d8c39384736aed115',
 'de70a70594664df0a72d3f2e3b099e4e',
 'dfee2b67074041cfbd208fdee9e49173',
 'a8aff0b211bf4604a1d538275e873477',
 '929a21a79c064405a1ccd299fbc1e007',
 '7a31effcdb1b44029666019afa560077',
 'a3b6917559734b80bc109638999155a1',
 '652fc9757d3245ef84e5ae5551e1e549',
 'ac3b816d3b54479fa83af9e336c2a528',
 'b9fad0b276c54958990a7fd5828ac2b8',
 '7e40af9c2096467ba1c0fc182558b4fe',
 '23b57ea97b2143419793cc796a37b49b',
 '664a07b1c4ad4967951be462d1abe0e4',
 '2b07d7044cfc4b9291df6dad6e65a1ce',
 'c125191b1f704254a59dfeae05781b22',
 '734f94f6da8d49398abae5b4f37c477b',
 '7f13ce1313fb4a9fb54088ede568bd09',
 'c1e9f1d2b95947df9d7e491179af4b03',
 'a385593445d741a0b9a7c0b120736de1',
 '5f2aad6e953348e999bc66981be2a87b',
 '196b9eeef30c49dc9a25a9e3350deffc',
 '34c40f8d5c50489e95ff4444fc9e220e',
 '168894fc0d724e0ea8a60cb0a74db26d',
 '314657adf7f84e19b331a5821c85939d',
 'cde715940ca94bd298fe23c22748050e',
 'aff2dc7ceac94d49b119806a7b01ded8',
 '9c5bcd171d864613bd0b676153cb0437',
 '00c042710b8a4b24ac02b93a6cb39393',
 '635b19de4c384de48d9dedf231bb67c5',
 '2fbf0e47c4794a1caaff980eda89cd5e',
 'ed52865b19464f9582b35c1f9ea7f3f8',
 'a567ea6da5c34c71abbe2c3bda322135',
 'd2018951a92d4176af924d7a0bc9be18',
 '3d1213c82e264f37bc0061ba1a591d2b',
 'e9703e52522c45c4963288023828460c',
 '77540edde2d94c3cb0144b7366ce7baf',
 '3d9338d3fe6b4f89ab4c23825db788d1',
 'cd5a3e19e92e43f186b96deb46bf3ac4',
 '737ffd2521c2486d8774780126777ccd',
 'd6b111552a584ac6be8c5a11114e362f',
 'b83fa0b921fa4b1db5ac980974471e7c',
 'fcb3e054d4a5474996f4d12f6e69914c',
 'a364f49c7d904552adf17b295364980e',
 '28b266dd63754e588a8ce35643152b2b',
 'fb20a30c47fc4653b33b7b4757979cfc',
 'eac89918f3ad455fbe368342bec95b39',
 '622e0e8362a041b5ae6e6af5ad7e154f',
 '24e1410e9a064811b138160d33509e4d',
 '8578ea93fa5e4ccc8ee3b992a0648896',
 '13eb2a873934423f947f1ee09ce1c637',
 'b26549a56b3543cf8ac9c23dc64d2392',
 '5ce7aa7984ff4247bb3a82418f39a7ae',
 '8bce9ed328a144b3944dfd6d61750395',
 '88e8cd28907b4407849e18eb4c7dd9db',
 '4f95a113736b4bd5835c63e89f14ab49',
 '5836a24ed867410eab513cfe83db7a87',
 '923ae9cdd797417bad16211d6e060fff',
 'a7846fce6ab54fb1871c6b87ac02ccc5',
 'f2f538373d0f40f9937e5428574a7b62',
 'ac011723bb944f228c3124a7d18230c5',
 'a96454f06a9b4df7b67fe495e978274e',
 '44f824a974bd4c18b77da408594344a9',
 '9500a30a48a4422fb460b8f8f233b0d0',
 '016d596a0382496da009b6765fa999bf',
 '9adf08a9ad324318a9adb677e456fcdc',
 '563fbbefe99049cdac65ba5bf9797f77',
 'c63ffd72c9ce400f8abd625701293811',
 '9c42a7f414ff499cab6719844401ae4a',
 'f0b301464120412c9f75623c870063db',
 '5aa57d6ea98d49adaed4d3960d66daf9',
 'cdb4e658cc4445fa8b4a74f7dfbd748a',
 '0d36a44bd1fd40408a8c2355d72c378a',
 'b16bd5ab99d34a7cabc291daa7daf43a',
 'bcac53915e1d4ecbbbcec287612649b6',
 '8b85795070104dde99d398746365d538',
 'ea3e45b4c9e3433c8ca7c86dfa852077',
 'b3eb4160bdf8426e8be8440d6f8b9299',
 'c432d4d0e476445a8aa6fb7681afd03b',
 '830f43ce1f6d4113942abc6522d7f163',
 '5504f879b27447ad8d1d179b5eb17678',
 '8cdd486448ba4275a7d895010a67e4c1',
 'ddb6c5ef21a44b7195157e55cddc74c6',
 '4a5fb8dfcb414de38a643c66abf900f6',
 'f3f4cda1cc0a408895270248773e68a2',
 '787be71db23d4200b44b0e6223ad6b22',
 '4e906046fa5e47a9b93a4621105b8ce9',
 'fb96a1393a1449cab098043340e3daf0',
 '0ab7ecd389a947fdb28a247a60be4817',
 'f75c2f60150344ceb918593b3703320f',
 '76ac5b27c8054c58bc4c014d3867fa55',
 'e089fe6fbdfc484da55bbaec0af9d62a',
 'bc5cd0c0516b4c3a86bb8bc7fe7dbafa',
 '877fbd53f67942a4b9338ca0d99d5e10',
 '6bfae0426b1c4dc4b74267784f2d4cf5',
 '0b86cbfc4a134925884fe748509cdc58',
 '230916cf858d466e995fb4eb290b83c9',
 '77fd3b6ffa594ae88844b57ad0c363bb',
 'bf8b884ca2ef4fc4b0f4c91f97127479',
 '414288d77aab4e14bf8c7576ea96caf0',
 'f09c6de3cb494c18827b88ab55d2f9d8',
 '129c78caa744477e930c3edcf358c77f',
 'f0c30c5664a144068728e03dc3272a0b',
 'ca9b9dff121145de925860780ba468b5',
 '6a4806d52e2a4b67ac7c67eb83c98001',
 'baaff17732f5455299df295b59f3549f',
 '1cbb36536077433485b9006072dea20c',
 '79b5735e14a34efeb0e43f290ffcaeee',
 '3ba5081c26eb4e41b888355bd5242a61',
 '37cfe6d4ed194ec9b595a0255f9835df',
 'ac4644ce2ca54f73b0823d1a6dfb98f2',
 'd0a89e87a62241adbc611a9c8a152309',
 '6f22b222c5d548479e05d7b7d525d728',
 '2fdbace3f84c4be6985b2db812df6b5f',
 '77009abe84fb4ee6964a8067550923c1',
 '399cdc267ba34a8e904f0b70d7228471',
 'cdd934da9258435f96be5ddf689a99d0',
 '5f6a4632b1944f16a9770177524abdda',
 '20056202459e4aa5b122cb3eb73c3fe0',
 'd835aebbb7f144df880f559bf6f37def',
 'a511382ea9e54ead8f0633f92295c464',
 '8072b54695f24e95a5bd71a31f16fe80',
 '8da1337ea6af4aebb472e8ba6b503e5e',
 'ea9d6299a9bc4c7a96fec172784c300c',
 'cc55883f9631490db98cd705681e9323',
 '7193db6a2fcd46d68a2acc9b9f421210',
 'd682c9cce8d14c7680bbd9f714334cd1',
 '81f5fb6cc23f4b3a85b542c0a93f4f46',
 'efbf2aa274e34ec7ac64c2770fa855e8',
 'd74be53d76ab4255b64878be9cbbd749',
 '4ad4da77dc824cebbd210d8e943c4931',
 'e9a5e034db4640d68a90ad21cfd8d290',
 '57dc3a2cffef4998a6d2870906044108',
 'b8f165afcdb6423d9a92b1e2d1632719',
 '2d9906b1467a4c24acdb0f15a7494199',
 '8d611c87c9f64aa2a8fd2828d6bc4fb5',
 '00aae5041abf4510a9409d4859390999',
 'd439701d04a5472da958124b21e966e2',
 'de2586b2b6744096a4d650d5af5fc5cf',
 '3f633e1cc21944f582796268f61f9781',
 'f4a757f796124aa9b25d0ea34bceeffa',
 '9d2d2e107c2d4f5d92e49ea2f85db4b1',
 'b3cbe3ae84344a3781ff3e15cec0cdd3',
 '4912c6f445b349d5bf6fe7b4d2fc68f6',
 '01ca587124eb4250bea78a14e6f4df43',
 'd75c3835e8aa4a838a7663c9b4e7c2a0',
 '35ac41ec02534dc3ba22c4e6d5fef387',
 '2bfb8abcb4984576a663e440ef351059',
 'c9900bbbfd994a3e9d4c71a258a9fbb3',
 'a146a5e873be475c9d117907529b6272',
 '83bcbbafa1a0402484b55c1095b9eb3d',
 'de4717f66f6442efb1c7b4e546b3c2c6',
 '485e43b38bbd42d99ce518d19f1ada96',
 '99e81c0fd63b43a58dd57a4db12b4e8e',
 'e4541a46e9bb49db916f171740c3120b',
 'c77973573b174204a4e6d696d2a8951a',
 '9768c3a52800444bbb4405cd3bba565d',
 'b827807393dd4ba289b7ab5064a79ac9',
 '0ccddbac47934f01aa9c3ee7a82fc7df',
 '4bb07419b19143baadac11ad40d3b42e',
 '281a162ad11840cdb07e31db8681726a',
 '48411c05f73a4a39ae22c8c0f0c1ea09',
 '3903333b9a4644be9f90d732bc175257',
 'c6e7bbd827d14551bd4140fff916d6b8',
 'd71f8555b9e04e288bf6d6840119eb4d',
 'fa1107261ce6434bb913e0a8afb7d7ae',
 '1713f433da8346b5a9ba56c743e7a9bc',
 '580e550ea4924a6787380fbbeab313d1',
 '8fd62b1cb49845d0b0f2e008d7d81566',
 '41eae4bbb3254891bb1b67e8958a70f0',
 '517160da549e47ad9ec2e9b8c9afe9dc',
 'b364f094eab84c37aa7a311f728d4d31',
 'ef35eecec541406d83efa167fcaab4bb',
 '953378f700194ef891d13b2da258878e',
 '288c1cda789d4b6984377e18a1255202',
 '1d4308d2ed97416d9d2c38bb9ff65690',
 'e50f092777f64ae88ebfd813107b9389',
 '250ba15f711c48f9a6bb8265251f4731',
 '9d8b215384a442d4bf909a65b863aa03',
 '03a19cd984f748df8658651f4574a315',
 '802ae473790b43c5be4b51455293d72c',
 '97f1e51569824c96932ecfa7b0a9337e',
 'fd06e07c227a4b15b15e2611050e8002',
 'c7417cc3de11469aa54829a53825dae9',
 '46d416acc24040b0bb68c575ba9c250a',
 '764d49115d104670b8ea59ee8a952bb2',
 '3b923c96c74645a0ba0873e28b146a95',
 '15a889c25f3b4cfea5a58dfcc79356e1',
 '220f6f1d86a240878704be99fd41ff8f',
 '945f2ffa0ce341baa5763786ad3f7534',
 'b9483a35bc25446f97ae8c9d89653c6b',
 '9ad22b08d87d4fee9e595d7f24486d8d',
 '2df57c9066f1454b8e7cf6ee357ef36b',
 '29153c14e47145a9b0f055d0407549b3',
 'f4f15b7038164a5a8e2a5971ed21b107',
 '442d9674599c4cd49a825369d2ff48ae',
 'b9861295072d4c34a439e6aed5a2e4cd',
 'bb28e7b2a3114eb38562255203a9a3a0',
 'be72d8e0551c4c94b6b728e0e2567b21',
 '30934b38b18d4d17887a23684e695f27',
 '17d6dc118e3e4960b93845c436b6760d',
 'd576a831e6e34a8fa96c49c01aedbdf3',
 '1a3182e823794479b5af22e49f146661',
 '8ed3f2d6f0e5428fae33777d486dc6f0',
 '728a2975088440feae78a9e71f99adcc',
 '1970197d1b734c1b907b7b6ec6eb608d',
 '21c1ecc0d47b4d2cadbf0377fe05fee3',
 'ca21a2dc580a4a77bb473e9ece331f79',
 'f0c6f1c96f684652b9056aba8bcbdff9',
 '03c796d3df4c4907bc0ebe56b3103559',
 'a095dc2367044074b4f14cc91f38c201',
 '96a46655a9074ae9abff34ce25becc5d',
 '80ed82cee89a4d889aee2e2718bf77a0',
 'c7c0edd2ae7946239cca93547bc25e6f',
 '9c91ab6e2086450bba4f38894d72272f',
 'ba12125b18c94df2805eba98710dcf32',
 '5f113337f9034a578a8f176576fa54ab',
 'bb89f3917d3c40368250fc1c8f32d47a',
 'fe09e84a07bd46cfb062d8b380f84a13',
 '43f8a1c9292b4f2ea749362b6baa279b',
 'e6919c2aa56e4236be181851d903bff5',
 '2e253090c7b4461284f9e915f50ee88d',
 '99bb37676b3b495da06818ccf43ea373',
 'e3c15e6b5eda46d9917f0db1290665e0',
 'e5047442610d4ad5b745337b6b42a95f',
 'c6a3693a5e3840be9019f1a01f25fc11',
 'c5bbaeea79d24cf38fbe8a18afe30b12',
 'f51efa9829594dc1b49a8375a7481136',
 '7a18880afad342cba5ab51187722186b',
 'eda9d9b1cfa14e0cbcdf2feced6b0a04',
 'a399653fa04346e1a0d884ffaf5ed713',
 '5bd62abfe28f446584180ddeec7028ec',
 '0e62cf2fb4e44221bce3ae82839f844a',
 'a8524bf81d874aa2a644a3c401a62abe',
 'e084a24120794a548228a5815e3a740c',
 '51282b9c2ff24abcbac07e4675a2bad1',
 'f8ab2395a6cb424ca1104a8aa929b7c2',
 '3bb261ba88554ab6a61424f329620828',
 'b93a1288389c4b6987f2f726f53e5ee5',
 '672dca5f807f414099e9d5582ad9f662',
 '0ba4c8f9bcde447eb268ab996fc53b4e',
 '5684f6adbbbb4f8f8205c094cfc30fa0',
 '42a848781b3e4a8f9d80e9ff2f4a7ae5',
 '4e38adbf6c064612b86fdbfa5c7d3eb1',
 '3e507f26f205469bb16d1390f417c768',
 'c336eab5c75d4363981f95113edf1e97',
 'e2e188943a27422084de0adeb375b600',
 '7b3ebf010f724020a82ebf3e29b6d7d4',
 '38e00081decb466aa7544f825348f639',
 '14b57fd91d084f2bb827c4e7cbbfa03b',
 'f637e61c0a8f416f974d1732f11775bd',
 '992635e3e82f4429934583e44f750c20',
 'fcbc2ebafe2748408583ba05c5a5c855',
 '4f76aa167eb24cd8a711bfa41bc62f7b',
 'a95c1dcea2254f9cab6090ac033676c2',
 '26d17448c2cd491d8ec4e7a5ec12e4ca',
 'f461734ae80c44bba57f93421d33ae27',
 '08e0835678994c218293462a8534771a',
 '6ba7a6221f95419fbc7bc2277c3d037e',
 '8f2c6f7f844b4dd29d27f5822bf001ff',
 '386abe8c0aaf48de98476f27b2673585',
 'ec58264d303d4d428e2efa9d652fa16d',
 '01572d80aea945d1bdfcae399a2a02a1',
 '0c33b3a982bd48f3b3affba472b5f135',
 '410cce87b66f416f83073e396046166d',
 '05a56bbdde674b11b4a8d78211b0458f',
 '939b912a86b449a2b36571f8fad51a5a',
 '0f6fe27141ec41f8afe144eabb5269a9',
 'cb193ad982ce403fa4434cc1b3aa1f2c',
 '7a6efe242d8a4cee800d4bdea8e80d66',
 'b989c3e7e253434581cadae9d62c8c80',
 '152cab55cf9e4100ad764c968287793b',
 '6dad0571520e4ddaacfba501e0bfdb21',
 'c5f29d9dda9a411c855472dfa4570188',
 'c0b9aa913a814d03a8adeb6a66b8fa96',
 '69354ff07c9d48d1907a1e0ce8dec46e',
 'e295c02c95f14e1da8cf3c312e4e630f',
 '3b750bab77af4b62b686e5309962ccba',
 'be7410da7f6e4db186da0d7e72a14ad8',
 'ead30e83200b4a8d8f94625762657fd6',
 'afa6b24546b74e5594f546b7c3ac5b8d',
 '96cff9908ad14b20a2d771cbcbc34433',
 'd6b9db95ca064654be6d058e35403c80',
 '9ac88fafff1544c5936aed73be106b29',
 '79c9fb2ab46e4c1dac6c955bdb7136a7',
 '8c5b302e8aa648c2956da45d5ab4ffd4',
 '91e3e88eb012415eab72ad4c03b8bd74',
 'c0ed32ba0aa4457591ca4f9c207fb01c',
 'c1dbae2d206a4b919a5e6dde4a5c1675',
 '8938b5a4b6ee428eab28ea83a77d258b',
 '7eeb3f3255444026871fd335c2689dba',
 'd9fe16c0376e4b8db403c90f2ce56878',
 'e60cba648ab1414db1ef7dd9620c2fd1',
 '621480553e214de1964e12497672f41c',
 'f664f189d0734aa3956ea806dfba8c83',
 '9730fc322dc448cabe88b3d7fa57738a',
 'f2b36cb1a80243f99cbe46d3196bdd23',
 'a24e6cd2431a4b9ba8f744ef21964a08',
 'cd8dadcecbff4ee7bbcd249e7a3f5a27',
 '177165f36fc74ff3a724754a439cdd52',
 'b6218453fcd74d21b07ebfde798d929d',
 'cda62ee3f8d044888efeda4d480241a4',
 '7ccec783cf60424e8cd8e65e476c6544',
 'e42e9a260ef5469294b4bd870793eac7',
 '1c4e1996c10d49e39053a761ab482ace',
 '3b1bac33c0714503a9eb51f6d7fbeccd',
 'e29883b727954ac99baf9a50a01f7989',
 '33ed643cd412495a82c6ece669bb67dd',
 '69dffddeb33641e6a5313cecf774bc74',
 '660ec25748f24d85bfcff0f9f2c33065',
 'a964fe48037746d389a06059072d3877',
 'b9a1ce7406224c3fb1990fd69ae42f17',
 '6b27379268f54a4e88bf223996e89383',
 '79fc87b548ac4aab9bf939bed911c93c',
 'e684a660a0994e57a16d4e0daa191ba3',
 '41d8e270a5b242a894eeefdf5d83eb9d',
 'b4fde8fbbd964464b4af49b368974687',
 '9226d800dcf5464e8ab5d62948679b7b',
 '67951040e03b46e9bb28f088af0f40f2',
 'f39251752f794483a50ba07eacc08f80',
 '5ff12744b3284301a0868324364a0684',
 '19e9325561e24c6197820814d500a2c2',
 'f9799e0f79754a258a6f817e01c18378',
 '69634977286244f8829be7855f11c222',
 'c25785c463004c2c9c20ef53f46ef847',
 '4c2930ba735441068c5bc6e6a181f20b',
 '776c91f558a944e281df0b1b93a7ba31',
 '32eb6b6445764c4686236bd73cd1c01a',
 '37e208646ef9485a88b2385bb949d7dd',
 '67b79336eb3940a48ee6c2371c274a39',
 '87a76b176b9749eaaf179d6196399600',
 '273d6b12b2464cc1a8c8f30b5cd39a3c',
 '096813ef03774a50a6aa7844ab37aaf9',
 'aa7d7726bf594c968b92d7c3ad256d8c',
 'b140e7025fcc4e819af7e9fbe2c07f3e',
 '28ab53b91298480d9e2015c11c02fca8',
 '0c4ab14edbbb460997073be921acb9dc',
 'dd81f7a66722400aae8f53ca2f611fb6',
 'd18414d26d434640a0c5b9bd94e5ce41',
 'b93e8b7aa4f74530b2cc20f7a38b67fd',
 '79395a3922964074bce749ef712c1bbf',
 '969cfab7ae64449a9bff288552607318',
 '421b82c6ecfc4ba5817fa8ab751b08ad',
 '3a4489a5beca40beac8fedd0d5160365',
 'e57d19e48c83434da927f90c6817066a',
 '2271e8b1884a40db9e94a1838b4244ad',
 '4cae6419f1cd49ca965d2fff4e488fb6',
 'c2f513c1d20f43daa4ffe8840b13f8ca',
 '5394c8f074d84ee99ef780479780e4a0',
 '11f00a4727d345048d333060688757cd',
 '5949f4a5f7e84fa29970baf496c594ec',
 '89ea243fcd264cc996b6e48ff2f5391b',
 '154bb74261bc4c928b71ed6d0aee30a0',
 'b28b8915ce2047588d70a352b906d6ef',
 '8417eabc523043ab83656605e60bcb59',
 'f13e4c1da76640d4a632025aa2ed084d',
 '728122f81fd24b1ab497dfb0cfa2304b',
 'e643eda9a6f1422da90f4a89d6f4b248',
 'a21aa4849646401993cf506feb2a392f',
 'af5bde46e6b6473e8ccc2cf90c77a012',
 'fc9cb631e4b040f9b6ae0ac4bc459469',
 '4599101d9baf43d391c98feacfdc1ac0',
 'd438037786be47ffaa295cda4ce51ad1',
 'fe132be13cb9476dbf6c5470a530a109',
 '310d94bf4dd84d86b9a1c7d6cba47ddf',
 '2b61e6099e1a42c7a91643d977477f32',
 'd4ae241994d240a1872aaa141c959fe4',
 'fc441557820946d8b9c0ac1edd0792b0',
 'b6f09db1aa1c4608889cbaaddf2f9d98',
 'e80d4c3689fc4d1eb559ab2ae25222e4',
 'eb6bdd2f20364a5b9700dff9cf930371',
 '49339950bd1c4061b462000eaabb0678',
 '61d98a90336b4ec5aa46b579e3afb874',
 'c1c4ec3d99854d6283a81787da0f36b0',
 '48a7331f38f14d93bc4b791cf8f805ff',
 '6a6ea241c94e45a78f9742fa3e7c9986',
 '98789f72bf274616b561053c435cf1fb',
 '91d28c97c232420f925d548fc004e1c0',
 '2e8b550d8dc046f48cbdb1526c06c580',
 '3b007b905aee4e1d9072ff57bb3894a1',
 'dea6c0d42203460c98e654d38191a24a',
 '3353883a283844659618b4ae396cc045',
 '7495045606874056b82d01b0169e29eb',
 '5533061e86ba4f92a39a2e9fa647db9e',
 'd2a7395dfe0348bb8221ab35d48bdf19',
 '32310f5961604b0da647643e7c76930f',
 'a6c2f3ce06b84854b9e25a181a74f837',

In [5]:
users[999]

'98b7d24f0c9849f29fc18290bde887de'

In [6]:
random.randint(1000000000 , 2000000000)

1410669421

In [15]:
df.loc[0]['5']

166

In [20]:
with open('kurtiData.csv', 'w' , encoding = 'utf-8' , newline='') as f:
    write = csv.writer(f)
    parameters = ['user_id' , 'product_id' , 'price' , 'rating' , 'timestamp']
    write.writerow(parameters)
    for i in range(0,180):
        temp = set([])
        for j in range(0,df.loc[i]['5']):
            index = random.randint(0,1499)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 5
                l5 = [user , product , price , rating , timestamp]
                write.writerow(l5)
            else : continue
                
        for j in range(0,df.loc[i]['4']):
            index = random.randint(0,1499)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 4
                l4 = [user , product , price , rating , timestamp]
                write.writerow(l4)
            else : continue
        
        for j in range(0,df.loc[i]['3']):
            index = random.randint(0,1499)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 3
                l3 = [user , product , price , rating , timestamp]
                write.writerow(l3)
            else : continue
                
        for j in range(0,df.loc[i]['2']):
            index = random.randint(0,1499)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 2
                l2 = [user , product , price , rating , timestamp]
                write.writerow(l2)
            else : continue
                
                
        for j in range(0,df.loc[i]['1']):
            index = random.randint(0,1499)
            if(index not in temp):
                temp.add(index)
                user = users[index]
                product = df.loc[i]['prod_id']
                price = df.loc[i]['price']
                timestamp = random.randint(1000000000 , 2000000000)
                rating = 1
                l1 = [user , product , price , rating , timestamp]
                write.writerow(l1)
            else : continue

In [21]:
dataset = pd.read_csv('kurtiData.csv')
dataset.head()

                            user_id product_id price  rating   timestamp
0  879e47a2d2864eb7b5b44e985d796f90     1xiamj  ₹293       5  1220150908
1  1041f5597bb7408fb8d06e8841bad8cc     1xiamj  ₹293       5  1672366450
2  4e8de5029ba145a2833d7826fa94f72e     1xiamj  ₹293       5  1217957331
3  4a5fb8dfcb414de38a643c66abf900f6     1xiamj  ₹293       5  1260132205
4  00ac6f52d1a840f4a3c1bdefcd205b66     1xiamj  ₹293       5  1493160005

In [ ]:
# for i in range(0 , 12762):
#     dataset.loc[i][price] = dataset.loc[i]['price'].replace('₹','')