In [2]:
import pandas as pd
import csv

In [3]:
dataset = pd.read_csv('kurtiData.csv')
dataset.head()

,user_id,product_id,product_url,image_url,price,rating,timestamp
0,0b32cb93b4d1467a895fdd0c0fdcac7d,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1816526580
1,a546c81dcb9346619c00f3632bb39318,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1431790209
2,6f7480ff712d42eb9be53f37641a3bf9,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1455698017
3,cf05abc75bd74b159bc91a76ad4bfbb5,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1419335880
4,893a87b0ef41435cbd40f5065bdff448,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1195975318

In [5]:
num_rating_df = dataset.groupby('product_id').count()['rating'].reset_index()
num_rating_df

    product_id  rating
0       100jt3    1500
1       105mbl    4647
2       108m4r     535
3       108o0m       9
4       108skr     404
..         ...     ...
941      z7l3y      41
942      ze031     204
943      zgxlp    2436
944      zqe9o     970
945      zs19v      30

[946 rows x 2 columns]

In [8]:
avg_rating_df = dataset.groupby('product_id').mean()['rating'].reset_index()
avg_rating_df

    product_id    rating
0       100jt3  3.432000
1       105mbl  3.631375
2       108m4r  3.642991
3       108o0m  3.222222
4       108skr  3.732673
..         ...       ...
941      z7l3y  4.219512
942      ze031  3.941176
943      zgxlp  3.713054
944      zqe9o  3.739175
945      zs19v  3.933333

[946 rows x 2 columns]

In [10]:
popular_df = avg_rating_df[num_rating_df['rating']>=250].sort_values('rating',ascending=False).head(50)
popular_df

    product_id    rating
778      epxlp  4.455591
345     2cdo61  4.320819
788      g8p4p  4.292683
781      fcpk0  4.250774
81      15uiwy  4.212257
400     2eypbl  4.211082
736      6tdsh  4.198830
769      busa3  4.191103
280     235q39  4.186933
774      cncck  4.186158
172     1c1wnf  4.183020
912      x5ift  4.181648
810      nxrj3  4.155285
766      bn7pz  4.150720
191     1j7xvc  4.146293
76      15lquu  4.132383
201     1n62ij  4.130360
919      xpuga  4.123026
233     1v05vs  4.116511
199     1lo4t6  4.111952
768      bnnlr  4.107312
917      xjxdr  4.082019
772      c585d  4.078033
826      pasbx  4.077472
795      iunbc  4.075342
841      qxxoj  4.069579
799      k87q3  4.066554
833      q3puz  4.066079
779      eud3r  4.063020
186     1gu6gq  4.061538
307     28i2s8  4.060134
724      48rzj  4.058660
302     26a70i  4.053659
223     1sme02  4.053116
604     2xs130  4.047101
935      z32x5  4.044000
171     1c18in  4.033105
272     21exhl  4.032258
250     1xdlka  4.030568
96      16j7sk  4.030211
220     1sbme8  4.028424
750      9all9  4.028190
408     2f854p  4.024259
303     26sm3q  4.015630
306     27omrn  3.997207
741      77fni  3.994410
405     2f387o  3.994100
235     1v0rpu  3.993151
740      754ly  3.991334
308     28jk6y  3.987910